package com.chen.beeaudio.utils

interface MyEmoji

/* 脸部表情
*  */
enum class FaceEmoji(
    val emojiContext: String,
    val emojiDescription: String
) : MyEmoji {
    GRINNING_FACE_WITH_BIG_SMILE("\uD83D\uDE03","哈哈"),
    GRINNING_FACE_WITH_LARGE_SMILE("😄","大笑"),
    GRINNING_FACE_WITH_SMILE_EYES("\uD83D\uDE01", "嘻嘻"),
    GRINNING_FACE_WITH_SQUINTING("\uD83D\uDE06", "斜眼笑"),
    GRINNING_FACE_WITH_SWEAT("\uD83D\uDE05", "苦笑"),
    ROLL_ON_THE_FLOOR_LAUGHING("\uD83E\uDD23", "笑得满地打滚"),
    FACE_WITH_TEARS_OF_JOY("\uD83D\uDE02", "笑哭"),
    SLIGHTLY_SMILE_FACE("\uD83D\uDE42", "呵呵"),
    UPSIDE_DOWN_FACE("\uD83D\uDE43", "倒脸"),
    WINKING_FACE("\uD83D\uDE09", ""),
    SMILING_FACE_WITH_SMILING("\uD83D\uDE0A", "羞涩微笑"),
    SMILING_FACE_WITH_HALO("😇", "微笑天使"),
    SMILING_FACE_WITH_HEARTS("\uD83E\uDD70", "喜笑颜开"),
    SMILING_FACE_WITH_HEARTS_EYES("\uD83D\uDE0D", "花痴"),
    STAR_STRUCK("\uD83E\uDD29", "好崇拜哦"),
    KISSING_FACE("\uD83D\uDE17", "亲亲"),
    SMILE_FACE("☺️", "微笑"),
    SMILING_FACE_WITH_TEAR("\uD83E\uDD72", "含泪微笑"),
    FACE_SAVORING_FOOD("\uD83D\uDE0B", "好吃"),
    WINKING_FACE_WITH_TONGUE("\uD83D\uDE1C", "单眼吐舌"),
    ZANY_FACE("\uD83E\uDD2A", "滑稽"),
    SQUINTING_FACE_WITH_TONGUE("\uD83D\uDE1D", "眯眼吐舌"),
    MONEY_MOUTH_FACE("\uD83E\uDD11", "发财"),
    SMILING_FACE_WITH_OPEN_HAND("\uD83E\uDD17", "抱抱"),
    FACE_WITH_HAND_OVER_MOUTH("\uD83E\uDD2D", "不说"),
    SHUSHING_FACE("\uD83E\uDD2B", "安静的脸"),
    THINKING_FACE("\uD83E\uDD14", "想一想"),
    ZIPPER_MOUTH_FACE("\uD83E\uDD10", "闭嘴"),
    FACE_WITH_RAISED_EYEBROW("\uD83E\uDD28", "挑眉"),
    NEUTRAL_FACE("\uD83D\uDE10", "冷漠"),
    EXPRESSIONLESS_FACE("\uD83D\uDE11", "无语"),
    FACE_WITH_MOUTH("\uD83D\uDE36", "沉默"),
    SMIRKING_FACE("\uD83D\uDE0F", "得意"),
    UNAMUSED_FACE("\uD83D\uDE12", "不高兴"),
    FACE_WITH_ROLLING_EYES("\uD83D\uDE44","翻白眼"),
    GRIMACING_FACE("\uD83D\uDE2C", "呲牙咧嘴"),
    LYING_FACE("\uD83E\uDD25", "说谎"),
    FACE_IN_CLOUDS("\uD83E\uDD25", "迷茫"),
    FACE_EXHALING("\uD83D\uDE2E\u200D\uD83D\uDCA8", "叹气"),
    RELIEVED_FACE("\uD83D\uDE0C", "送了口气"),
    PENSIVE_FACE("\uD83D\uDE0C", "沉思"),
    SLEEPY_FACE("\uD83D\uDE2A", "困"),
    DROOLING_FACE("\uD83E\uDD24", "流口水"),
    SLEEPING_FACE("\uD83D\uDE34", "睡着了"),
    FACE_WITH_MEDICAL_MASK("\uD83D\uDE37", "感冒"),
    FACE_WITH_THERMOMETER("\uD83E\uDD12", "发烧"),
    FACE_WITH_HEAD_BANDAGE("\uD83E\uDD15", "受伤"),
    NAUSEATED_FACE("\uD83E\uDD22", "恶心"),
    FACE_VOMITING("\uD83E\uDD2E", "呕吐"),
    SNEEZING_FACE("\uD83E\uDD27", "打喷嚏"),
    HOT_FACE("\uD83E\uDD75", "脸发烧"),
    COLD_FACE("\uD83E\uDD76", "冷脸"),
    WOOZY_FACE("\uD83E\uDD74", "头眼昏花"),
    FACE_WITH_CROSSED_OUT_EYES("\uD83D\uDE35", "晕头转向"),
    EXPLODING_HEAD("\uD83E\uDD2F", "爆炸头"),
    FACE_WITH_SPIRAL_EYES("\uD83D\uDE35\u200D\uD83D\uDCAB", "晕"),
    COWBOY_HAT_FACE("\uD83E\uDD20", "牛仔表情"),
    PARTYING_FACE("\uD83E\uDD73", "聚会笑脸"),
    DISGUISED_FACE("\uD83E\uDD78", "伪装的脸"),
    SMILING_FACE_WITH_SUNGLASSES("\uD83D\uDE0E", "墨镜笑脸"),
    NERD_FACE("\uD83E\uDD13", "书呆子脸"),
    FACE_WITH_MONOCLE("\uD83E\uDDD0", "带单片眼镜的脸"),
    CONFUSED_FACE("\uD83D\uDE15", "困扰"),
    WORRIED_FACE("\uD83D\uDE1F", "担心"),
    SLIGHTLY_FROWNING_FACE("\uD83D\uDE41", "微微不满"),
    FROWNING_FACE("☹️", "不满"),
    FACE_WITH_OPEN_MOUTH("\uD83D\uDE2E", "吃惊"),
    ASTONISHED_FACE("\uD83D\uDE32", "震惊"),
    FLUSHED_FACE("\uD83D\uDE33", "脸红"),
    PLEADING_FACE("\uD83E\uDD7A", "恳求的脸"),
    FROWNING_FACE_WITH_OPEN_MOUTH("\uD83D\uDE26", "啊"),
    ANGUISHED_FACE("\uD83D\uDE27", "极度痛苦"),
    FEARFUL_FACE("\uD83D\uDE28", "害怕"),
    ANXIOUS_FACE_WITH_SWEAT("\uD83D\uDE30", "冷汗"),
    SAD_BUT_RELIEVED_FACE("\uD83D\uDE25", "失望但如释重负"),
    CRYING_FACE("\uD83D\uDE22", "哭脸"),
    LOUDLY_CRYING_FACE("\uD83D\uDE2D", "放声大哭"),
    FACE_SCREAMING_IN_DEAR("\uD83D\uDE31", "吓死了"),
    CONFOUNDED_FACE("\uD83D\uDE16","困惑"),
    PERSEVERING_FACE("\uD83D\uDE23", "痛苦"),
    DISAPPOINTED_FACE("\uD83D\uDE1E", "失望"),
    DOWNCAST_FACE_WITH_SWEAT("\uD83D\uDE13", "汗"),
    WEARY_FACE("\uD83D\uDE29", "累死了"),
    TIRED_FACE("\uD83D\uDE2B", "打哈欠"),
    YAWNING_FACE("🥱", "打哈欠"),
    FACE_WITH_STEAM_FROM_NOSE("\uD83D\uDE24", "傲慢"),
    ENRAGED_FACE("\uD83D\uDE21", "怒火中烧"),
    ANGRY_FACE("\uD83D\uDE20", "生气"),
    FACE_WITH_SYMBOLS_ON_MOUTH("\uD83E\uDD2C", "嘴上有符号的脸"),
    SMILING_FACE_WITH_HORNS("\uD83D\uDE08", "恶魔微笑"),
    ANGRY_FACE_WITH_HORNS("\uD83D\uDC7F", "恶魔生气"),
    SKULL("\uD83D\uDC80", "头骨"),
    SKULL_AND_CROSSBONES("☠️", "骷髅"),
    PILE_OF_POO("\uD83D\uDCA9", "大便"),
    CLOWN_FACE("\uD83E\uDD21", "小丑"),
    OGRE("\uD83D\uDC79", "食人魔"),
    GOBLIN("\uD83D\uDC7A", "小妖精"),
    GHOST("\uD83D\uDC7B", "鬼"),
    ALIEN("\uD83D\uDC7D", "外星人"),
    ALIEN_MONSTER("\uD83D\uDC7E", "外星怪物"),
    ROBOT("\uD83E\uDD16", "机器人")
}

/* 身体部位 */
enum class BodyEmoji(
    val emojiContext: String,
    val emojiDescription: String
) : MyEmoji {
    WAVING_HAND("\uD83D\uDC4B", "挥手"),
    RAISED_BACK_OF_HAND("\uD83E\uDD1A", "手背"),
    HAND_WITH_FINGERS_SPLAYED("\uD83D\uDD90️", "手掌"),
    RAISED_HAND("✋", "举起手"),
    VULCAN_SALUTE("\uD83D\uDD96", "瓦肯举手礼"),
    OK_HAND("\uD83D\uDC4C", "OK"),
    PINCHING_HAND("\uD83E\uDD0F", "捏合的手势"),
    VICTORY_HAND("✌️", "胜利手势"),
    CROSSED_FINGERS("\uD83E\uDD1E", "交叉的手指"),
    LOVE_YOU_GESTURE("\uD83E\uDD1F", "爱你的手势"),
    SIGN_OF_THE_HORNS("\uD83E\uDD18", "摇滚"),
    CALL_ME_HAND("\uD83E\uDD19", "给我给我打电话"),
    PINCHED_FINGERS("\uD83E\uDD0C", "捏手指"),
    BACKHAND_INDEX_POINTING_LEFT("\uD83D\uDC48", "反手食指向左指"),
    BACKHAND_INDEX_POINTING_RIGHT("\uD83D\uDC49", "反向食指向右指"),
    BACKHAND_INDEX_POINTING_UP("\uD83D\uDC46", "反向食指向上指"),
    MIDDLE_FINGER("\uD83D\uDD95", "竖中指"),
    BACKHAND_INDEX_POINTING_DOWN("\uD83D\uDC47", "反向食指向下指"),
    INDEX_POINTING_UP("☝️", "食指向上指"),
    THUMBS_UP("\uD83D\uDC4D", "拇指向上"),
    THUMBS_DOWN("\uD83D\uDC4E", "拇指向下"),
    RAISED_FIST("✊", "举起拳头"),
    ONCOMING_FIST("\uD83D\uDC4A", "出拳"),
    LEFT_FACING_FIST("\uD83E\uDD1B", "朝左的拳头"),
    RIGHT_FACING_FIST("\uD83E\uDD1C", "朝右的拳头"),
    CLAPPING_HANDS("\uD83D\uDC4F", "鼓掌"),
    RAISING_HANDS("\uD83D\uDE4C", "举双手"),
    OPEN_HANDS("\uD83D\uDC50", "张开双手"),
    PALMS_UP_TOGETHER("\uD83E\uDD32", "掌心向上托起"),
    HAND_SHAKE("\uD83E\uDD1D", "握手"),
    FOLDED_HANDS("\uD83D\uDE4F", "双手合十"),
    WRITING_HAND("✍️", "写字"),
    NAIL_POLISH("\uD83D\uDC85","涂指甲油"),
    SELFIE("\uD83E\uDD33", "自拍"),
    FLEXED_BICEPS("\uD83D\uDCAA", "肌肉"),
    MECHANICAL_ARM("\uD83E\uDDBE", "机械手臂"),
    MECHANICAL_LEG("\uD83E\uDDBF", "机械腿"),
    LEG("\uD83E\uDDB5", "腿"),
    FOOT("\uD83E\uDDB6", "脚"),
    EAR("\uD83D\uDC42", "耳朵"),
    EAR_WITH_HEARING_AID("\uD83E\uDDBB", "戴助听器的耳朵"),
    NOSE("\uD83D\uDC43", "鼻子"),
    BRAIN("\uD83E\uDDE0", "脑"),
    TOOTH("\uD83E\uDDB7", "牙齿"),
    BONE("\uD83E\uDDB4", "骨头"),
    EYES("\uD83D\uDC40", "双眼"),
    EYE("\uD83D\uDC41️", "眼睛"),
    TONGUE("\uD83D\uDC45", "舌头"),
    MOUTH("\uD83D\uDC44", "嘴"),
    ANATOMICAL_HEART("\uD83E\uDEC0", "心脏"),
    LUNG("\uD83E\uDEC1", "肺"),
    PERSON_FROWNING("\uD83D\uDE4D", "皱眉"),
    PERSON_POUTING("\uD83D\uDE4E", "撅嘴"),
    PERSON_GESTURING_NO("\uD83D\uDE45", "禁止手势"),
    PERSON_GESTURING_OK("\uD83D\uDE46", "OK手势"),
    PERSON_TIPPING_HAND("\uD83D\uDC81", "前台"),
    PERSON_RAISING_HAND("\uD83D\uDE4B", "举手"),
    DEAF_PERSON("\uD83E\uDDCF", "失聪者"),
    PERSON_BOWING("\uD83D\uDE47", "鞠躬"),
    PERSON_FACE_PLAMING("\uD83E\uDD26", "捂脸"),
    PERSON_SHRUGGING("\uD83E\uDD37", "耸肩"),
}

/* 虚构人物 */
enum class RoleEmoji(
    val emojiContext: String,
    val emojiDescription: String
) : MyEmoji {
    BABY_ANGEL("\uD83D\uDC7C", "小天使"),
    SANTA_CLAUS("\uD83C\uDF85", "圣诞老人"),
    MRS_CLAUS("\uD83E\uDD36", "圣诞奶奶"),
    SUPERHERO("\uD83E\uDDB8", "超级英雄"),
    SUPER_VILLAIN("\uD83E\uDDB9", "超级坏蛋"),
    MAGE("\uD83E\uDDD9", "法师"),
    FAIRY("\uD83E\uDDDA", "精灵"),
    VAMPIRE("\uD83E\uDDDB", "吸血鬼"),
    MER_PERSON("\uD83E\uDDDC", "人鱼"),
    ELF("\uD83E\uDDDD", "小精灵"),
    GENIE("\uD83E\uDDDE", "妖怪"),
    ZOMBIE("\uD83E\uDDDF", "僵尸"),
}

/* 动物表情 */
enum class AnimalEmoji(
    val emojiContext: String,
    val emojiDescription: String
) : MyEmoji {
    MONKEY_FACE("\uD83D\uDC35", "猴脸"),
    MONKEY("\uD83D\uDC12", "猴子"),
    GORILLA("\uD83E\uDD8D", "大猩猩"),
    ORANGUTAN("\uD83E\uDDA7", "红毛星星"),
    DOG_FACE("\uD83D\uDC36", "狗脸"),
    DOG("\uD83D\uDC15", "狗"),
    GUIDE_DOG("\uD83E\uDDAE", "导盲犬"),
    POODLE("\uD83D\uDC29", "贵宾犬"),
    WOLF("\uD83D\uDC3A", "狼"),
    FOX("\uD83E\uDD8A", "狐狸"),
    RACCOON("\uD83E\uDD9D", "浣熊"),
    CAT_FACE("\uD83D\uDC31", "猫脸"),
    CAT("\uD83D\uDC08", "猫"),
    LION("\uD83E\uDD81", "狮子"),
    TIGER_FACE("\uD83D\uDC2F", "虎头"),
    TIGER("\uD83D\uDC2F", "老虎"),
    LEOPARD("\uD83D\uDC06", "豹子"),
    HORSE_FACE("\uD83D\uDC34", "马头"),
    HORSE("\uD83D\uDC0E", "马"),
    UNICORN("\uD83E\uDD84", "独角兽"),
    ZEBRA("\uD83E\uDD93", "斑马"),
    DEER("\uD83E\uDD8C", "鹿"),
    COW_FACE("\uD83D\uDC2E", "奶牛头"),
    OX("\uD83D\uDC02", "公牛"),
    WATER_BUFFALO("\uD83D\uDC03", "水牛"),
    COW("\uD83D\uDC04", "奶牛"),
    PIG_FACE("\uD83D\uDC37", "猪头"),
    PIG("\uD83D\uDC16", "猪"),
    BOAR("\uD83D\uDC17", "野猪"),
    PIG_NOSE("\uD83D\uDC3D", "猪鼻子"),
    RAM("\uD83D\uDC0F", "公羊"),
    EWE("\uD83D\uDC11", "母羊"),
    GOAT("\uD83D\uDC10", "山羊"),
    CAMEL("\uD83D\uDC2A", "骆驼"),
    TWO_HUMP_CAMEL("\uD83D\uDC2B", "双峰骆驼"),
    LLAMA("\uD83E\uDD99", "美洲驼"),
    GIRAFFE("\uD83E\uDD92", "长颈鹿"),
    ELEPHANT("\uD83D\uDC18", "大象"),
    RHINOCEROS("\uD83E\uDD8F", "犀牛"),
    HIPPOPOTAMUS("\uD83E\uDD9B", "河马"),
    MOUSE_FACE("\uD83D\uDC2D", "老鼠头"),
    MOUSE("\uD83D\uDC01", "老鼠"),
    RAT("\uD83D\uDC00", "耗子"),
    HAMSTER("\uD83D\uDC39", "仓鼠"),
    RABBIT_FACE("\uD83D\uDC30", "兔子头"),
    RABBIT("\uD83D\uDC07", "兔子"),
    CHIPMUNK("\uD83D\uDC3F", "松鼠"),
    NEDGEHOG("\uD83E\uDD94", "刺猬"),
    BAT("\uD83E\uDD87", "蝙蝠"),
    BEAR("\uD83D\uDC3B", "熊"),
    KOALA("\uD83D\uDC28", "考拉"),
    PANDA("\uD83D\uDC3C", "熊猫"),
    SLOTH("\uD83E\uDDA5", "树懒"),
    OTTER("\uD83E\uDDA6", "水獭"),
    SKUNK("\uD83E\uDDA8", "臭鼬"),
    KANGAROO("\uD83E\uDD98", "袋鼠"),
    BADGER("\uD83E\uDDA1", "獾"),
    PAW_PRINTS("\uD83D\uDC3E", "爪印"),
    BISON("\uD83E\uDDAC", "大野牛"),
    MAMMOTH("\uD83E\uDDA3", "猛犸"),
    BEAVER("\uD83E\uDDAB", "海狸"),
    TURKEY("\uD83E\uDD83", "火鸡"),
    CHICKEN("\uD83D\uDC14", "鸡"),
    ROOSTER("\uD83D\uDC13", "公鸡"),
    HATCHING_CHICK("\uD83D\uDC23", "小鸡破壳"),
    BABY_CHICK("\uD83D\uDC24", "小鸡"),
    FRONT_FACING_BABY_CHICK("\uD83D\uDC25", "正面朝向的小鸡"),
    BIRD("\uD83D\uDC26", "鸟"),
    PENGUIN("\uD83D\uDC27", "企鹅"),
    DOVE("\uD83D\uDD4A", "鸽"),
    EAGLE("\uD83E\uDD85", "鹰"),
    DUCK("\uD83E\uDD86", "鸭子"),
    SWAN("\uD83E\uDDA2", "天鹅"),
    OWL("\uD83E\uDD89", "猫头鹰"),
    FLAMINGO("\uD83E\uDDA9", "火烈鸟"),
    PEACOCK("\uD83E\uDD9A", "孔雀"),
    PARROT("\uD83E\uDD9C", "鹦鹉"),
    DODO("\uD83E\uDDA4", "渡渡鸟"),
    FEATHER("\uD83E\uDEB6", "羽毛"),
    FROG("\uD83D\uDC38", "青蛙"),
    CROCODILIE("\uD83D\uDC0A", "鳄鱼"),
    TURTLE("\uD83D\uDC22", "龟"),
    LIZARD("\uD83E\uDD8E", "蜥蜴"),
    SNAKE("\uD83D\uDC0D", "蛇"),
    DRAGON_FACE("\uD83D\uDC32", "龙头"),
    DRAGON("\uD83D\uDC09", "龙"),
    SAUROPOD("\uD83E\uDD95", "蜥蜴类"),
    T_REX("\uD83E\uDD96", "霸王龙"),
    SPOUTING_WHALE("\uD83D\uDC33", "喷水的鲸"),
    WHALE("\uD83D\uDC0B", "鲸"),
    DOLPHIN("\uD83D\uDC2C", "海豚"),
    FISH("\uD83D\uDC1F", "鱼"),
    TROPICAL_FISH("\uD83D\uDC20", "热带鱼"),
    BLOW_FISH("\uD83D\uDC21", "河豚"),
    SHARK("\uD83E\uDD88", "鲨鱼"),
    OCTOPUS("\uD83D\uDC19", "章鱼"),
    SPIRAL_SHELL("\uD83D\uDC1A", "海螺"),
    SEAL("\uD83E\uDDAD", "海豹"),
    SNAIL("\uD83D\uDC0C", "蜗牛"),
    BUTTERFLY("\uD83E\uDD8B", "蝴蝶"),
    BUG("\uD83D\uDC1B", "毛毛虫"),
    ANT("\uD83D\uDC1C", "蚂蚁"),
    HONEYBEE("\uD83D\uDC1D", "蜂蜜"),
    LADY_BEETLE("\uD83D\uDC1E", "瓢虫"),
    CRICKET("\uD83E\uDD97", "蟋蟀"),
    SPIDER("\uD83D\uDD77", "蜘蛛"),
    SPIDER_WEB("\uD83D\uDD78", "蜘蛛网"),
    SCORPION("\uD83E\uDD82", "蝎子"),
    MOSQUITO("\uD83E\uDD9F", "蚊子"),
    MICROBE("\uD83E\uDDA0", "细菌"),
    BEETLE("\uD83E\uDEB2", "甲虫"),
    COCKROACH("\uD83E\uDEB3", "蟑螂"),
    FLY("\uD83E\uDEB0", "苍蝇"),
    WORM("\uD83E\uDEB1", "蠕虫"),
    BOUQUET("\uD83D\uDC90", "花束"),
    CHERRY_BLOSSOM("\uD83C\uDF38", "樱花"),
    WHITE_FLOWER("\uD83D\uDCAE", "白花"),
    ROSETTE("\uD83C\uDFF5", "圆形花饰"),
    ROSE("\uD83C\uDF39", "玫瑰"),
    WILTED_FLOWED("\uD83E\uDD40", "枯萎的花"),
    HIBISCUS("\uD83C\uDF3A", "芙蓉"),
    SUNFLOWER("\uD83C\uDF3B", "向日葵"),
    BLOSSOM("\uD83C\uDF3C", "开花"),
    TULIP("\uD83C\uDF37", "郁金香"),
    SEEDLING("\uD83C\uDF31", "幼苗"),
    EVERGREEN_TREE("\uD83C\uDF32", "松树"),
    DECIDUOUS_TREE("\uD83C\uDF33", "落叶树"),
    PALM_TREE("\uD83C\uDF34", "棕榈树"),
    CACTUS("\uD83C\uDF35", "仙人掌"),
    SHEAF_OF_RICE("\uD83C\uDF3E", "稻子"),
    HERB("\uD83C\uDF3F", "药草"),
    SHAMROCK("☘️", "三叶草"),
    FOUR_LEAF_CLOVER("\uD83C\uDF40", "四叶草"),
    MAPLE_LEAF("\uD83C\uDF41", "枫叶"),
    FALLEN_LEAF("\uD83C\uDF42", "落叶"),
    LEAF_FLUTTERING_IN_WIND("\uD83C\uDF43", "风吹叶落"),
    POTTED_PLANT("\uD83E\uDEB4", "盆栽植物")
}

/* 食物表情 */
enum class FoodEmoji(
    val emojiContext: String,
    val emojiDescription: String
) : MyEmoji {
    GRAPES("\uD83C\uDF47", "葡萄"),
    MELON("\uD83C\uDF48", "甜瓜"),
    WATERMELON("\uD83C\uDF49", "西瓜"),
    TANGERINE("\uD83C\uDF4A", "橘子"),
    LEMON("\uD83C\uDF4B", "柠檬"),
    BANANA("\uD83C\uDF4C", "香蕉"),
    PINEAPPLE("\uD83C\uDF4D", "菠萝"),
    MANGO("\uD83E\uDD6D", "芒果"),
    RED_APPLE("\uD83C\uDF4E", "红苹果"),
    GREEN_APPLE("\uD83C\uDF4F", "青苹果"),
    PEAR("\uD83C\uDF50", "梨"),
    PEACH("\uD83C\uDF51", "桃"),
    CHERRIES("\uD83C\uDF52", "草莓"),
    KIWI_FRUIT("\uD83E\uDD5D", "猕猴桃"),
    TOMATO("\uD83C\uDF45", "西红柿"),
    COCONUT("\uD83E\uDD65","椰子"),
    BLUEBERRIES("\uD83E\uDED0", "蓝莓"),
    OLIVE("\uD83E\uDED2", "橄榄"),
    AVOCADO("\uD83E\uDD51", "鳄梨"),
    EGGPLANT("\uD83C\uDF46", "茄子"),
    POTATO("\uD83E\uDD54", "土豆"),
    CARROT("\uD83E\uDD55", "胡萝卜"),
    EAR_OF_CORN("\uD83C\uDF3D", "玉米"),
    HOT_PEPPER("\uD83C\uDF36️", "红辣椒"),
    CUCUMBER("\uD83E\uDD52", "黄瓜"),
    LEAFY_GREEN("\uD83E\uDD6C", "绿叶蔬菜"),
    BROCCOLI("\uD83E\uDD66", "西兰花"),
    GARLIC("\uD83E\uDDC4", "蒜"),
    ONION("\uD83E\uDDC5", "洋葱"),
    MUSHROOM("\uD83C\uDF44", "蘑菇"),
    PEANUT("\uD83E\uDD5C", "花生"),
    CHESTNUT("\uD83C\uDF30", "栗子"),
    BELL_PEPPER("\uD83E\uDED1", "灯笼椒"),
    BREAD("\uD83C\uDF5E", "面包"),
    CROISSANT("\uD83E\uDD50", "羊角面包"),
    BAGUETTE_BREAD("\uD83E\uDD56", "法式长棍面包"),
    PRETZEL("\uD83E\uDD68", "椒盐卷饼"),
    BAGEL("\uD83E\uDD6F", "面包圈"),
    PANCAKES("\uD83E\uDD5E", "烙饼"),
    WAFFLE("\uD83E\uDDC7", "华夫饼"),
    CHEESE_WEDGE("\uD83E\uDDC0","芝士"),
    MEAT_ON_BONE("\uD83C\uDF56", "排骨"),
    POULTRY_LEG("\uD83C\uDF57", "家禽的腿"),
    CUT_OF_MEAT("\uD83E\uDD69", "肉块"),
    BACON("\uD83E\uDD53", " 培根"),
    HAMBURGER("\uD83E\uDD53", "汉堡"),
    FRENCH_FRIES("\uD83C\uDF5F", "薯条"),
    PIZZA("\uD83C\uDF55", "披萨"),
    HOT_DOG("\uD83C\uDF2D", "热狗"),
    SANDWICH("\uD83E\uDD6A", "三明治"),
    TACO("\uD83C\uDF2E", "墨西哥卷饼"),
    BURRITO("\uD83C\uDF2F", "墨西哥卷饼"),
    STUFFED_FLATBREAD("\uD83E\uDD59", "夹心饼"),
    FALAFEL("\uD83E\uDDC6", "炸豆丸子"),
    EGG("\uD83E\uDD5A", "蛋"),
    COOKING("\uD83C\uDF73", "煎蛋"),
    SHALLOW_PAN_OF_FOOD("\uD83E\uDD58", "装有食物的锅"),
    POT_OF_FOOD("\uD83C\uDF72", "一锅食物"),
    BOWL_WITH_SPOON("\uD83E\uDD63", "碗勺"),
    GREEN_SALAD("\uD83E\uDD57", "绿色沙拉"),
    POPCORN("\uD83C\uDF7F", "爆米花"),
    BUTTER("\uD83E\uDDC8", "黄油"),
    SALT("\uD83E\uDDC2", "盐"),
    CANNED_FOOD("\uD83E\uDD6B", "罐头食品"),
    FLATBREAD("\uD83E\uDED3", "扁面包"),
    TAMALE("\uD83E\uDED4", "墨西哥粽子"),
    FONDUE("\uD83E\uDED5", "奶酪火锅"),
    BENTO_BOX("\uD83C\uDF71", "盒饭"),
    RICE_CRACKER("\uD83C\uDF58", "米饭"),
    RICE_BALL("\uD83C\uDF59", "饭团"),
    COOKED_RICE("\uD83C\uDF5A", "米饭"),
    CURRY_RICE("\uD83C\uDF5B", "咖喱饭"),
    STEAMING_BOWL("\uD83C\uDF5C", "面条"),
    SPAGHETTI("\uD83C\uDF5D", "意粉"),
    ROASTED_SWEET_POTATO("\uD83C\uDF60", "烤红薯"),
    ODEN("\uD83C\uDF62", "关东煮"),
    SUSHI("\uD83C\uDF63", "寿司"),
    FRIED_SHRIMP("\uD83C\uDF64", "天妇罗"),
    FISH_CAKE_WITH_SWIRL("\uD83C\uDF65", "鱼板"),
    MOON_CAKE("\uD83E\uDD6E", "月饼"),
    DANGO("\uD83C\uDF61", "团子"),
    DUMPLING("\uD83E\uDD5F", "饺子"),
    FORTUNE_COOKIE("\uD83E\uDD60", "幸运饼干"),
    TAKEOUT_BOX("\uD83E\uDD61", "外卖盒子"),
    CARB("\uD83E\uDD80", "蟹"),
    LOBSTER("\uD83E\uDD9E", "龙虾"),
    SHRIMP("\uD83E\uDD90", " 虾"),
    SQUID("\uD83E\uDD91", "乌贼"),
    OYSTER("\uD83E\uDDAA", "牡蛎"),
    SOFT_ICE_CREAM("\uD83C\uDF66", "甜筒冰淇淋"),
    SHAVED_ICE("\uD83C\uDF67", "刨冰"),
    ICE_CREAM("\uD83C\uDF68", "冰淇淋"),
    DOUGHNUT("\uD83C\uDF69", "甜甜圈"),
    COOKIE("\uD83C\uDF6A", "饼干"),
    BIRTHDAY_CAKE("\uD83C\uDF82", "生日蛋糕"),
    SHORT_CAKE("\uD83C\uDF70", "水果蛋糕"),
    CUP_CAKE("\uD83E\uDDC1", "制备蛋糕"),
    PIE("\uD83E\uDD67", "派"),
    CHOCOLATE("\uD83C\uDF6B", "巧克力"),
    CANDY("\uD83C\uDF6C", "糖"),
    LOLLIPOP("\uD83C\uDF6D", "棒棒糖"),
    CUSTARD("\uD83C\uDF6E", "蜂蜜"),
    HONEY_POT("\uD83C\uDF6F", "蜂蜜"),
    BABY_BOTTLE("\uD83C\uDF7C", "奶瓶"),
    GLASS_OF_MILK("\uD83E\uDD5B", "一杯奶"),
    HOT_BEVERAGE("☕", "热饮"),
    TEACUP_WITH_HANDLE("\uD83C\uDF75", "热茶"),
    SAKE("\uD83C\uDF76", "清酒"),
    BOTTLE_WITH_POPPING_CORK("\uD83C\uDF7E", "开香槟"),
    WINE_GLASS("\uD83C\uDF77", "葡萄酒"),
    COCKTAIL_GLASS("\uD83C\uDF78", "鸡尾酒"),
    TROPICAL_DRINK("\uD83C\uDF79", "热饮水果饮料"),
    BEER_MUG("\uD83C\uDF7A", "啤酒"),
    CLINKING_BEER_MUGS("\uD83C\uDF7B", "干杯"),
    CLINKING_GLASSES("\uD83E\uDD42", " 碰杯"),
    TUMBLER_GLASS("\uD83E\uDD43", "平底杯"),
    CUP_WITH_STRAW("\uD83E\uDD64", "带吸管杯"),
    BEVERAGE_BOX("\uD83E\uDDC3", "饮料盒"),
    MATE("\uD83E\uDDC9", "马黛茶"),
    ICE("\uD83E\uDDCA", "冰块"),
    TEAPOT("\uD83E\uDED6", "茶壶"),
    BUBBLE_TEA("\uD83E\uDDCB", "珍珠奶茶"),
    CHOPSTICKS("\uD83E\uDD62", "筷子"),
    FORK_AND_KNIFE_WITH_PLATE("\uD83C\uDF7D", "餐具"),
    FORK_AND_KNIFE("\uD83C\uDF74", "刀叉"),
    SPOON("\uD83E\uDD44", "匙"),
    KITCHEN("\uD83D\uDD2A", "菜刀"),
    AMPHORA("\uD83C\uDFFA", "双耳瓶")
}

/* 活动表情 */
enum class ActivityEmoji(
    val emojiContext: String,
    val emojiDescription: String
) : MyEmoji {
    JACK_O_LANTERN("\uD83C\uDF83", "南瓜灯"),
    CHRISTMAS_TREE("\uD83C\uDF84", "圣诞树"),
    FIREWORKS("\uD83C\uDF86", "焰火"),
    SPARKLER("\uD83C\uDF87", "烟花"),
    FIRECRACKER("\uD83E\uDDE8", "爆竹"),
    SPARKLES("✨", "闪亮"),
    BALLOON("\uD83C\uDF88", "气球"),
    PARTY_POPPER("🎉", "拉炮彩带"),
    CONFETTI_BALL("🎊", "五彩纸屑球"),
    TANABATA_TREE("🎋", "七夕树"),
    PINE_DECORATION("🎍", "门松"),
    JAPANESE_DOLLS("🎎", "日本人形"),
    CARP_STREAMER("🎏", "鲤鱼旗"),
    WIND_CHIME("🎐", "风铃"),
    MOON_VIEWING_CEREMONY("🎑", "赏月"),
    RED_ENVELOPE("🧧", "红包"),
    RIBBON("🎀", "蝴蝶结"),
    WRAPPED_GIFT("🎁", "礼物"),
    REMINDER_RIBBON("🎗️", "提示丝带"),
    ADMISSION_TICKETS("🎟️", "入场券"),
    TICKET("🎫", "票"),
    MILITARY_MEDAL("🎖️", "军功章"),
    TROPHY("🏆", "奖杯"),
    SPORTS_MEDAL("🏅", "奖牌"),
    ONE_ST_PLACE_MEDAL("🥇", "金牌"),
    TWOND_PLACE_MEDAL("🥈", "银牌"),
    THIRD_RD_PLACE_MEDAL("🥉", "铜牌"),
    SOCCER_BALL("⚽", "足球"),
    BASEBALL("⚾", "棒球"),
    SOFTBALL("🥎", "垒球"),
    BASKETBALL("🏀", "篮球"),
    VOLLEYBALL("🏐", "排球"),
    AMERICAN_FOOTBALL("🏈", "美式橄榄球"),
    RUGBY_FOOTBALL("🏉", "英式橄榄球"),
    TENNIS("🎾", "网球"),
    FLYING_DISC("🥏", "飞盘"),
    BOWLING("🎳", "保龄球"),
    CRICKET_GAME("🏏", "板球"),
    FIELD_HOCKEY("🏑", "曲棍球"),
    ICE_HOCKEY("🏒", "冰球"),
    LACROSSE("🥍", "袋棍球"),
    PING_PONG("🏓", "乒乓球"),
    BADMINTON("🏸", "羽毛球"),
    BOXING_GLOVE("🥊", "拳击手套"),
    MARTIAL_ARTS_UNIFORM("🥋", "练武服"),
    GOAL_NET("🥅", "球门"),
    FLAG_IN_HOLE("⛳", "高尔夫球洞"),
    ICE_SKATE("⛸️", "滑冰"),
    FISHING_POLE("🎣", "钓鱼竿"),
    DIVING_MASK("🤿", "潜水面罩"),
    RUNNING_SHIRT("🎽", "运动背心"),
    SKIS("🎿", "滑雪"),
    SLED("🛷", "雪橇"),
    CURLING_STONE("🥌", "冰壶"),
    BULLSEYE("🎯", "正中靶心的飞镖"),
    YO_YO("🪀", "悠悠球"),
    KITE("🪁", "风筝"),
    POOL_8_BALL("🎱", "台球"),
    CRYSTAL_BALL("🔮", "水晶球"),
    NAZAR_AMULET("🧿", "纳扎尔护身符"),
    VIDEO_GAME("🎮", "游戏手柄"),
    JOYSTICK("🕹️", "游戏操控杆"),
    SLOT_MACHINE("🎰", "老虎机"),
    GAME_DIE("🎲", "骰子"),
    PUZZLE_PIECE("🧩", "拼图"),
    TEDDY_BEAR("🧸", "泰迪熊"),
    SPADE_SUIT("♠️", "黑桃"),
    HEART_SUIT("♥️", "红桃"),
    DIAMOND_SUIT("♦️", "方片"),
    CLUB_SUIT("♣️", "梅花"),
    CHESS_PAWN("♟️", "兵"),
    JOKER("🃏", "大小王"),
    MAHJONG_RED_DRAGON("🀄", "红中"),
    FLOWER_PLAYING_CARDS("🎴", "花札"),
    MAGIC_WAND("🪄", "魔棒"),
    PIÑATA("🪅", "彩罐"),
    NESTING_DOLLS("🪆", "套娃"),
    PERFORMING_ARTS("🎭", "表演艺术"),
    FRAMED_PICTURE("🖼️", "带框的画"),
    ARTIST_PALETTE("🎨", "调色盘"),
    THREAD("🧵", "线"),
    YARN("🧶", "毛线"),
    SEWING_NEEDLE("🪡", "缝合针"),
    KNOT("🪢", "结"),
}

/* 旅行与地理表情 */
enum class PlaceEmoji(
    val emojiContext: String,
    val emojiDescription: String
) : MyEmoji {
    GLOBE_SHOWING_EUROPE_AFRICA("🌍", "地球上的欧洲非洲"),
    GLOBE_SHOWING_AMERICAS("🌎", "地球上的美洲"),
    GLOBE_SHOWING_ASIA_AUSTRALIA("🌏", "地球上的亚洲澳洲"),
    GLOBE_WITH_MERIDIANS("🌐", "带经纬线的地球"),
    WORLD_MAP("🗺️", "世界地图"),
    MAP_OF_JAPAN("🗾", "日本地图"),
    COMPASS("🧭", "指南针"),
    SNOW_CAPPED_MOUNTAIN("🏔️", "雪山"),
    MOUNTAIN("⛰️", "山"),
    VOLCANO("🌋", "火山"),
    MOUNT_FUJI("🗻", "富士山"),
    CAMPING("🏕️", "露营"),
    BEACH_WITH_UMBRELLA("🏖️", "沙滩伞"),
    DESERT("🏜️", "沙漠"),
    DESERT_ISLAND("🏝️", "无人荒岛"),
    NATIONAL_PARK("🏞️", "国家公园"),
    STADIUM("🏟️", "体育馆"),
    CLASSICAL_BUILDING("🏛️", "古典建筑"),
    BUILDING_CONSTRUCTION("🏗️", "施工"),
    BRICK("🧱", "砖"),
    HOUSES("🏘️", "房屋建筑"),
    DERELICT_HOUSE("🏚️", "废墟"),
    HOUSE("🏠", "房子"),
    HOUSE_WITH_GARDEN("🏡", "别墅"),
    OFFICE_BUILDING("🏢", "办公楼"),
    JAPANESE_POST_OFFICE("🏣", "日本邮局"),
    POST_OFFICE("🏤", "邮局"),
    HOSPITAL("🏥", "医院"),
    BANK("🏦", "银行"),
    HOTEL("🏨", "酒店"),
    LOVE_HOTEL("🏩", "情人酒店"),
    CONVENIENCE_STORE("🏪", "便利店"),
    SCHOOL("🏫", "学校"),
    DEPARTMENT_STORE("🏬", "商场"),
    FACTORY("🏭", "工厂"),
    JAPANESE_CASTLE("🏯", "日本城堡"),
    CASTLE("🏰", "欧洲城堡"),
    WEDDING("💒", "婚礼"),
    TOKYO_TOWER("🗼", "东京塔"),
    STATUE_OF_LIBERTY("🗽", "自由女神像"),
    ROCK("🪨", "岩石"),
    WOOD("🪵", "木头"),
    HUT("🛖", "小屋"),
    CHURCH("⛪", "教堂"),
    MOSQUE("🕌", "清真寺"),
    HINDU_TEMPLE("🛕", "印度寺庙"),
    SYNAGOGUE("🕍", "犹太教堂"),
    SHINTO_SHRINE("⛩️", "神社"),
    KAABA("🕋", "克尔白"),
    FOUNTAIN("⛲", "喷泉"),
    TENT("⛺", "帐篷"),
    FOGGY("🌁", "有雾"),
    NIGHT_WITH_STARS("🌃", "夜晚"),
    CITYSCAPE("🏙️", "城市风光"),
    SUNRISE_OVER_MOUNTAINS("🌄", "山顶日出"),
    SUNRISE("🌅", "日出"),
    CITYSCAPE_AT_DUSK("🌆", "城市黄昏"),
    SUNSET("🌇", "日落"),
    BRIDGE_AT_NIGHT("🌉", "夜幕下的桥"),
    HOT_SPRINGS("♨️", "温泉"),
    CAROUSEL_HORSE("🎠", "旋转木马"),
    FERRIS_WHEEL("🎡", "摩天轮"),
    ROLLER_COASTER("🎢", "过山车"),
    BARBER_POLE("💈", "理发店"),
    CIRCUS_TENT("🎪", "马戏团帐篷"),
    LOCOMOTIVE("🚂", "蒸汽火车"),
    RAILWAY_CAR("🚃", "轨道车"),
    HIGH_SPEED_TRAIN("🚄", "高速列车"),
    BULLET_TRAIN("🚅", "子弹头高速列车"),
    TRAIN("🚆", "火车"),
    METRO("🚇", "地铁"),
    LIGHT_RAIL("🚈", "轻轨"),
    STATION("🚉", "车站"),
    TRAM("🚊", "路面电车"),
    MONORAIL("🚝", "单轨"),
    MOUNTAIN_RAILWAY("🚞", "山区铁路"),
    TRAM_CAR("🚋", "有轨电车"),
    BUS("🚌", "公交车"),
    ONCOMING_BUS("🚍", "迎面驶来的公交车"),
    TROLLEYBUS("🚎", "无轨电车"),
    MINIBUS("🚐", "小巴"),
    AMBULANCE("🚑", "救护车"),
    FIRE_ENGINE("🚒", "消防车"),
    POLICE_CAR("🚓", "警车"),
    ONCOMING_POLICE_CAR("🚔", "迎面驶来的警车"),
    TAXI("🚕", "出租车"),
    ONCOMING_TAXI("🚖", "迎面驶来的出租车"),
    AUTOMOBILE("🚗", "汽车"),
    ONCOMING_AUTOMOBILE("🚘", "迎面驶来的汽车"),
    SPORT_UTILITY_VEHICLE("🚙", "运动型多用途车"),
    DELIVERY_TRUCK("🚚", "货车"),
    ARTICULATED_LORRY("🚛", "铰接式货车"),
    TRACTOR("🚜", "拖拉机"),
    RACING_CAR("🏎️", "赛车"),
    MOTORCYCLE("🏍️", "摩托车"),
    MOTOR_SCOOTER("🛵", "小型摩托车"),
    MANUAL_WHEELCHAIR("🦽", "手动轮椅"),
    MOTORIZED_WHEELCHAIR("🦼", "电动轮椅"),
    AUTO_RICKSHAW("🛺", "三轮摩托车"),
    BICYCLE("🚲", "自行车"),
    KICK_SCOOTER("🛴", "滑板车"),
    SKATEBOARD("🛹", "滑板"),
    BUS_STOP("🚏", "公交车站"),
    MOTORWAY("🛣️", "高速公路"),
    RAILWAY_TRACK("🛤️", "铁轨"),
    OIL_DRUM("🛢️", "石油桶"),
    FUEL_PUMP("⛽", "油泵"),
    POLICE_CAR_LIGHT("🚨", "警车灯"),
    HORIZONTAL_TRAFFIC_LIGHT("🚥", "横向的红绿灯"),
    VERTICAL_TRAFFIC_LIGHT("🚦", "纵向的红绿灯"),
    STOP_SIGN("🛑", "停止标志"),
    CONSTRUCTION("🚧", "路障"),
    PICKUP_TRUCK("🛻", "敞蓬小型载货卡车"),
    ROLLER_SKATE("🛼", "四轮滑冰鞋"),
    ANCHOR("⚓", "锚"),
    SAILBOAT("⛵", "帆船"),
    CANOE("🛶", "独木舟"),
    SPEEDBOAT("🚤", "快艇"),
    PASSENGER_SHIP("🛳️", "客轮"),
    FERRY("⛴️", "渡轮"),
    MOTOR_BOAT("🛥️", "摩托艇"),
    SHIP("🚢", "船"),
    AIRPLANE("✈️", "飞机"),
    SMALL_AIRPLANE("🛩️", "小型飞机"),
    AIRPLANE_DEPARTURE("🛫", "航班起飞"),
    AIRPLANE_ARRIVAL("🛬", "航班降落"),
    PARACHUTE("🪂", "降落伞"),
    SEAT("💺", "座位"),
    HELICOPTER("🚁", "直升机"),
    SUSPENSION_RAILWAY("🚟", "空轨"),
    MOUNTAIN_CABLEWAY("🚠", "缆车"),
    AERIAL_TRAMWAY("🚡", "索道"),
    SATELLITE("🛰️", "卫星"),
    ROCKET("🚀", "火箭"),
    FLYING_SAUCER("🛸", "飞碟"),
    BELLHOP_BELL("🛎️", "服务铃"),
    LUGGAGE("🧳", "行李箱"),
    HOURGLASS_DONE("⌛", "沙漏"),
    HOURGLASS_NOT_DONE("⏳", "沙正往下流的沙漏"),
    WATCH("⌚", "手表"),
    ALARM_CLOCK("⏰", "闹钟"),
    STOPWATCH("⏱️", "秒表"),
    TIMER_CLOCK("⏲️", "定时器"),
    MANTELPIECE_CLOCK("🕰️", "座钟"),
    TWELVE_O_CLOCK("🕛", "十二点"),
    TWELVE_THIRTY("🕧", "十二点半"),
    ONE_O_CLOCK("🕐", "一点"),
    ONE_THIRTY("🕜", "一点半"),
    TWO_O_CLOCK("🕑", "两点"),
    TWO_THIRTY("🕝", "两点半"),
    THREE_O_CLOCK("🕒", "三点"),
    THREE_THIRTY("🕞", "三点半"),
    FOUR_O_CLOCK("🕓", "四点"),
    FOUR_THIRTY("🕟", "四点半"),
    FIVE_O_CLOCK("🕔", "五点"),
    FIVE_THIRTY("🕠", "五点半"),
    SIX_O_CLOCK("🕕", "六点"),
    SIX_THIRTY("🕡", "六点半"),
    SEVEN_O_CLOCK("🕖", "七点"),
    SEVEN_THIRTY("🕢", "七点半"),
    EIGHT_O_CLOCK("🕗", "八点"),
    EIGHT_THIRTY("🕣", "八点半"),
    NINE_O_CLOCK("🕘", "九点"),
    NINE_THIRTY("🕤", "九点半"),
    TEN_O_CLOCK("🕙", "十点"),
    TEN_THIRTY("🕥", "十点半"),
    ELEVEN_O_CLOCK("🕚", "十一点"),
    ELEVEN_THIRTY("🕦", "十一点半"),
    NEW_MOON("🌑", "朔月"),
    WAXING_CRESCENT_MOON("🌒", "娥眉月"),
    FIRST_QUARTER_MOON("🌓", "上弦月"),
    WAXING_GIBBOUS_MOON("🌔", "盈凸月"),
    FULL_MOON("🌕", "满月"),
    WANING_GIBBOUS_MOON("🌖", "亏凸月"),
    LAST_QUARTER_MOON("🌗", "下弦月"),
    WANING_CRESCENT_MOON("🌘", "残月"),
    CRESCENT_MOON("🌙", "弯月"),
    NEW_MOON_FACE("🌚", "微笑的朔月"),
    FIRST_QUARTER_MOON_FACE("🌛", "微笑的上弦月"),
    LAST_QUARTER_MOON_FACE("🌜", "微笑的下弦月"),
    THERMOMETER("🌡️", "温度计"),
    SUN("☀️", "太阳"),
    FULL_MOON_FACE("🌝", "微笑的月亮"),
    SUN_WITH_FACE("🌞", "微笑的太阳"),
    RINGED_PLANET("🪐", "有环行星"),
    STAR("⭐", "星星"),
    GLOWING_STAR("🌟", "闪亮的星星"),
    SHOOTING_STAR("🌠", "流星"),
    MILKY_WAY("🌌", "银河"),
    CLOUD("☁️", "云"),
    SUN_BEHIND_CLOUD("⛅", "阴"),
    CLOUD_WITH_LIGHTNING_AND_RAIN("⛈️", "雷阵雨"),
    SUN_BEHIND_SMALL_CLOUD("🌤️", "晴偶有云"),
    SUN_BEHIND_LARGE_CLOUD("🌥️", "多云"),
    SUN_BEHIND_RAIN_CLOUD("🌦️", "晴转雨"),
    CLOUD_WITH_RAIN("🌧️", "下雨"),
    CLOUD_WITH_SNOW("🌨️", "下雪"),
    CLOUD_WITH_LIGHTNING("🌩️", "打雷"),
    TORNADO("🌪️", "龙卷风"),
    FOG("🌫️", "雾"),
    WIND_FACE("🌬️", "大风"),
    CYCLONE("🌀", "台风"),
    RAINBOW("🌈", "彩虹"),
    CLOSED_UMBRELLA("🌂", "收起的伞"),
    UMBRELLA("☂️", "伞"),
    UMBRELLA_WITH_RAIN_DROPS("☔", "雨伞"),
    UMBRELLA_ON_GROUND("⛱️", "阳伞"),
    HIGH_VOLTAGE("⚡", "高压"),
    SNOWFLAKE("❄️", "雪花"),
    SNOWMAN("☃️", "雪与雪人"),
    SNOWMAN_WITHOUT_SNOW("⛄", "雪人"),
    COMET("☄️", "彗星"),
    FIRE("🔥", "火焰"),
    DROPLET("💧", "水滴"),
    WATER_WAVE("🌊", "浪花"),
}

/* 物品表情 */
enum class ObjectEmoji(
    val emojiContext: String,
    val emojiDescription: String
) : MyEmoji {
    GLASSES("👓", "眼镜"),
    SUNGLASSES("🕶️", "墨镜"),
    GOGGLES("🥽", "护目镜"),
    LAB_COAT("🥼", "白大褂"),
    SAFETY_VEST("🦺", "救生衣"),
    NECKTIE("👔", "领带"),
    T_SHIRT("👕", "T恤"),
    JEANS("👖", "牛仔裤"),
    SCARF("🧣", "围巾"),
    GLOVES("🧤", "手套"),
    COAT("🧥", "外套"),
    SOCKS("🧦", "袜子"),
    DRESS("👗", "连衣裙"),
    KIMONO("👘", "和服"),
    SARI("🥻", "纱丽"),
    ONE_PIECE_SWIMSUIT("🩱", "连体泳衣"),
    BRIEFS("🩲", "三角裤"),
    SHORTS("🩳", "短裤"),
    BIKINI("👙", "比基尼"),
    WOMAN_S_CLOTHES("👚", "女装"),
    PURSE("👛", "钱包"),
    HANDBAG("👜", "手提包"),
    CLUTCH_BAG("👝", "手袋"),
    SHOPPING_BAGS("🛍️", "购物袋"),
    BACKPACK("🎒", "书包"),
    MAN_S_SHOE("👞", "男鞋"),
    RUNNING_SHOE("👟", "跑鞋"),
    HIKING_BOOT("🥾", "登山鞋"),
    FLAT_SHOE("🥿", "平底鞋"),
    HIGH_HEELED_SHOE("👠", "高跟鞋"),
    WOMAN_S_SANDAL("👡", "女式凉鞋"),
    BALLET_SHOES("🩰", "芭蕾舞鞋"),
    WOMAN_S_BOOT("👢", "女靴"),
    CROWN("👑", "皇冠"),
    WOMAN_S_HAT("👒", "女帽"),
    TOP_HAT("🎩", "礼帽"),
    GRADUATION_CAP("🎓", "毕业帽"),
    BILLED_CAP("🧢", "鸭舌帽"),
    RESCUE_WORKER_S_HELMET("⛑️", "白十字头盔"),
    PRAYER_BEADS("📿", "念珠"),
    LIPSTICK("💄", "唇膏"),
    RING("💍", "戒指"),
    GEM_STONE("💎", "宝石"),
    THONG_SANDAL("🩴", "夹趾凉鞋"),
    MILITARY_HELMET("🪖", "军用头盔"),
    MUTED_SPEAKER("🔇", "已静音的扬声器"),
    SPEAKER_LOW_VOLUME("🔈", "低音量的扬声器"),
    SPEAKER_MEDIUM_VOLUME("🔉", "中等音量的扬声器"),
    SPEAKER_HIGH_VOLUME("🔊", "高音量的扬声器"),
    LOUDSPEAKER("📢", "喇叭"),
    MEGAPHONE("📣", "扩音器"),
    POSTAL_HORN("📯", "邮号"),
    BELL("🔔", "铃铛"),
    BELL_WITH_SLASH("🔕", "禁止响铃"),
    MUSICAL_SCORE("🎼", "乐谱"),
    MUSICAL_NOTE("🎵", "音符"),
    MUSICAL_NOTES("🎶", "多个音符"),
    STUDIO_MICROPHONE("🎙️", "录音室麦克风"),
    LEVEL_SLIDER("🎚️", "电平滑块"),
    CONTROL_KNOBS("🎛️", "控制旋钮"),
    MICROPHONE("🎤", "麦克风"),
    HEADPHONE("🎧", "耳机"),
    RADIO("📻", "收音机"),
    SAXOPHONE("🎷", "萨克斯管"),
    GUITAR("🎸", "吉他"),
    MUSICAL_KEYBOARD("🎹", "音乐键盘"),
    TRUMPET("🎺", "小号"),
    VIOLIN("🎻", "小提琴"),
    BANJO("🪕", "班卓琴"),
    DRUM("🥁", "鼓"),
    ACCORDION("🪗", "手风琴"),
    LONG_DRUM("🪘", "长鼓"),
    MOBILE_PHONE("📱", "手机"),
    MOBILE_PHONE_WITH_ARROW("📲", "带有箭头的手机"),
    TELEPHONE("☎️", "电话"),
    TELEPHONE_RECEIVER("📞", "电话听筒"),
    PAGER("📟", "寻呼机"),
    FAX_MACHINE("📠", "传真机"),
    BATTERY("🔋", "电池"),
    ELECTRIC_PLUG("🔌", "电源插头"),
    LAPTOP("💻", "笔记本电脑"),
    DESKTOP_COMPUTER("🖥️", "台式电脑"),
    PRINTER("🖨️", "打印机"),
    KEYBOARD("⌨️", "键盘"),
    COMPUTER_MOUSE("🖱️", "电脑鼠标"),
    TRACKBALL("🖲️", "轨迹球"),
    COMPUTER_DISK("💽", "电脑光盘"),
    FLOPPY_DISK("💾", "软盘"),
    OPTICAL_DISK("💿", "光盘"),
    DVD("📀", "DVD"),
    ABACUS("🧮", "算盘"),
    MOVIE_CAMERA("🎥", "电影摄影机"),
    FILM_FRAMES("🎞️", "影片帧"),
    FILM_PROJECTOR("📽️", "电影放映机"),
    CLAPPER_BOARD("🎬", "场记板"),
    TELEVISION("📺", "电视机"),
    CAMERA("📷", "相机"),
    CAMERA_WITH_FLASH("📸", "开闪光灯的相机"),
    VIDEO_CAMERA("📹", "摄像机"),
    VIDEOCASSETTE("📼", "录像带"),
    MAGNIFYING_GLASS_TILTED_LEFT("🔍", "左斜的放大镜"),
    MAGNIFYING_GLASS_TILTED_RIGHT("🔎", "右斜的放大镜"),
    CANDLE("🕯️", "蜡烛"),
    LIGHT_BULB("💡", "灯泡"),
    FLASHLIGHT("🔦", "手电筒"),
    RED_PAPER_LANTERN("🏮", "红灯笼"),
    DIYA_LAMP("🪔", "印度油灯"),
    NOTEBOOK_WITH_DECORATIVE_COVER("📔", "精装笔记本"),
    CLOSED_BOOK("📕", "合上的书本"),
    OPEN_BOOK("📖", "打开的书本"),
    GREEN_BOOK("📗", "绿色书本"),
    BLUE_BOOK("📘", "蓝色书本"),
    ORANGE_BOOK("📙", "橙色书本"),
    BOOKS("📚", "书"),
    NOTEBOOK("📓", "笔记本"),
    LEDGER("📒", "账本"),
    PAGE_WITH_CURL("📃", "带卷边的页面"),
    SCROLL("📜", "卷轴"),
    PAGE_FACING_UP("📄", "文件"),
    NEWSPAPER("📰", "报纸"),
    ROLLED_UP_NEWSPAPER("🗞️", "报纸卷"),
    BOOKMARK_TABS("📑", "标签页"),
    BOOKMARK("🔖", "书签"),
    LABEL("🏷️", "标签"),
    MONEY_BAG("💰", "钱袋"),
    YEN_BANKNOTE("💴", "日元"),
    DOLLAR_BANKNOTE("💵", "美元"),
    EURO_BANKNOTE("💶", "欧元"),
    POUND_BANKNOTE("💷", "英镑"),
    MONEY_WITH_WINGS("💸", "长翅膀的钱"),
    CREDIT_CARD("💳", "信用卡"),
    RECEIPT("🧾", "收据"),
    CHART_INCREASING_WITH_YEN("💹", "趋势向上且带有日元符号的图表"),
    COIN("🪙", "硬币"),
    ENVELOPE("✉️", "信封"),
    E_MAIL("📧", "电子邮件"),
    INCOMING_ENVELOPE("📨", "来信"),
    ENVELOPE_WITH_ARROW("📩", "收邮件"),
    OUTBOX_TRAY("📤", "发件箱"),
    INBOX_TRAY("📥", "收件箱"),
    PACKAGE("📦", "包裹"),
    CLOSED_MAILBOX_WITH_RAISED_FLAG("📫", "有待收信件"),
    CLOSED_MAILBOX_WITH_LOWERED_FLAG("📪", "无待收信件"),
    OPEN_MAILBOX_WITH_RAISED_FLAG("📬", "有新信件"),
    OPEN_MAILBOX_WITH_LOWERED_FLAG("📭", "无新信件"),
    POSTBOX("📮", "邮筒"),
    BALLOT_BOX_WITH_BALLOT("🗳️", "投票箱"),
    PENCIL("✏️", "铅笔"),
    BLACK_NIB("✒️", "钢笔尖"),
    FOUNTAIN_PEN("🖋️", "钢笔"),
    PEN("🖊️", "笔"),
    PAINTBRUSH("🖌️", "画笔"),
    CRAYON("🖍️", "蜡笔"),
    MEMO("📝", "备忘录"),
    BRIEFCASE("💼", "公文包"),
    FILE_FOLDER("📁", "文件夹"),
    OPEN_FILE_FOLDER("📂", "打开的文件夹"),
    CARD_INDEX_DIVIDERS("🗂️", "索引分隔文件夹"),
    CALENDAR("📅", "日历"),
    TEAR_OFF_CALENDAR("📆", "手撕日历"),
    SPIRAL_NOTEPAD("🗒️", "线圈本"),
    SPIRAL_CALENDAR("🗓️", "线圈日历"),
    CARD_INDEX("📇", "卡片索引"),
    CHART_INCREASING("📈", "趋势向上的图表"),
    CHART_DECREASING("📉", "趋势向下的图表"),
    BAR_CHART("📊", "条形图"),
    CLIPBOARD("📋", "剪贴板"),
    PUSHPIN("📌", "图钉"),
    ROUND_PUSHPIN("📍", "圆图钉"),
    PAPERCLIP("📎", "回形针"),
    LINKED_PAPERCLIPS("🖇️", "连起来的两个回形针"),
    STRAIGHT_RULER("📏", "直尺"),
    TRIANGULAR_RULER("📐", "三角尺"),
    SCISSORS("✂️", "剪刀"),
    CARD_FILE_BOX("🗃️", "卡片盒"),
    FILE_CABINET("🗄️", "文件柜"),
    WASTEBASKET("🗑️", "垃圾桶"),
    LOCKED("🔒", "合上的锁"),
    UNLOCKED("🔓", "打开的锁"),
    LOCKED_WITH_PEN("🔏", "墨水笔和锁"),
    LOCKED_WITH_KEY("🔐", "钥匙和锁"),
    KEY("🔑", "钥匙"),
    OLD_KEY("🗝️", "老式钥匙"),
    HAMMER("🔨", "锤子"),
    AXE("🪓", "斧头"),
    PICK("⛏️", "铁镐"),
    HAMMER_AND_PICK("⚒️", "锤子与镐"),
    HAMMER_AND_WRENCH("🛠️", "锤子与扳手"),
    DAGGER("🗡️", "匕首"),
    CROSSED_SWORDS("⚔️", "交叉放置的剑"),
    WATER_PISTOL("🔫", "水枪"),
    BOW_AND_ARROW("🏹", "弓和箭"),
    SHIELD("🛡️", "盾牌"),
    WRENCH("🔧", "扳手"),
    NUT_AND_BOLT("🔩", "螺母与螺栓"),
    GEAR("⚙️", "齿轮"),
    CLAMP("🗜️", "夹钳"),
    BALANCE_SCALE("⚖️", "天平"),
    WHITE_CANE("🦯", "盲杖"),
    LINK("🔗", "链接"),
    CHAINS("⛓️", "链条"),
    TOOLBOX("🧰", "工具箱"),
    MAGNET("🧲", "磁铁"),
    BOOMERANG("🪃", "回旋镖"),
    CARPENTRY_SAW("🪚", "木工锯"),
    SCREWDRIVER("🪛", "螺丝刀"),
    HOOK("🪝", "挂钩"),
    LADDER("🪜", "梯子"),
    ALEMBIC("⚗️", "蒸馏器"),
    TEST_TUBE("🧪", "试管"),
    PETRI_DISH("🧫", "培养皿"),
    DNA("🧬", "DNA"),
    MICROSCOPE("🔬", "显微镜"),
    TELESCOPE("🔭", "望远镜"),
    SATELLITE_ANTENNA("📡", "卫星天线"),
    SYRINGE("💉", "注射器"),
    DROP_OF_BLOOD("🩸", "血滴"),
    PILL("💊", "药丸"),
    ADHESIVE_BANDAGE("🩹", "创可贴"),
    STETHOSCOPE("🩺", "听诊器"),
    DOOR("🚪", "门"),
    BED("🛏️", "床"),
    COUCH_AND_LAMP("🛋️", "沙发和灯"),
    CHAIR("🪑", "椅子"),
    TOILET("🚽", "马桶"),
    SHOWER("🚿", "淋浴"),
    BATHTUB("🛁", "浴缸"),
    RAZOR("🪒", "剃须刀"),
    LOTION_BOTTLE("🧴", "乳液瓶"),
    SAFETY_PIN("🧷", "安全别针"),
    BROOM("🧹", "扫帚"),
    BASKET("🧺", "筐"),
    ROLL_OF_PAPER("🧻", "卷纸"),
    SOAP("🧼", "皂"),
    SPONGE("🧽", "海绵"),
    FIRE_EXTINGUISHER("🧯", "灭火器"),
    SHOPPING_CART("🛒", "购物车"),
    ELEVATOR("🛗", "电梯"),
    MIRROR("🪞", "镜子"),
    WINDOW("🪟", "窗户"),
    PLUNGER("🪠", "活塞"),
    MOUSE_TRAP("🪤", "捕鼠器"),
    BUCKET("🪣", "桶"),
    TOOTHBRUSH("🪥", "牙刷"),
    CIGARETTE("🚬", "香烟"),
    COFFIN("⚰️", "棺材"),
    FUNERAL_URN("⚱️", "骨灰缸"),
    MOAI("🗿", "摩埃"),
    HEADSTONE("🪦", "墓碑"),
    PLACARD("🪧", "标语牌"),
}

/* 符号标志表情 */
enum class SymbolsEmoji(
    val emojiContext: String,
    val emojiDescription: String
) : MyEmoji {
    ATM_SIGN("🏧", "取款机"),
    LITTER_IN_BIN_SIGN("🚮", "倒垃圾"),
    POTABLE_WATER("🚰", "饮用水"),
    WHEELCHAIR_SYMBOL("♿", "轮椅标识"),
    MEN_S_ROOM("🚹", "男厕"),
    WOMEN_S_ROOM("🚺", "女厕"),
    RESTROOM("🚻", "卫生间"),
    BABY_SYMBOL("🚼", "宝宝"),
    WATER_CLOSET("🚾", "厕所"),
    PASSPORT_CONTROL("🛂", "护照检查"),
    CUSTOMS("🛃", "海关"),
    BAGGAGE_CLAIM("🛄", "提取行李"),
    LEFT_LUGGAGE("🛅", "寄存行李"),
    WARNING("⚠️", "警告"),
    CHILDREN_CROSSING("🚸", "儿童过街"),
    NO_ENTRY("⛔", "禁止通行"),
    PROHIBITED("🚫", "禁止"),
    NO_BICYCLES("🚳", "禁止自行车"),
    NO_SMOKING("🚭", "禁止吸烟"),
    NO_LITTERING("🚯", "禁止乱扔垃圾"),
    NON_POTABLE_WATER("🚱", "非饮用水"),
    NO_PEDESTRIANS("🚷", "禁止行人通行"),
    NO_MOBILE_PHONES("📵", "禁止使用手机"),
    NO_ONE_UNDER_EIGHTEEN("🔞", "18禁"),
    RADIOACTIVE("☢️", "辐射"),
    BIOHAZARD("☣️", "生物危害"),
    UP_ARROW("⬆️", "向上箭头"),
    UP_RIGHT_ARROW("↗️", "右上箭头"),
    RIGHT_ARROW("➡️", "向右箭头"),
    DOWN_RIGHT_ARROW("↘️", "右下箭头"),
    DOWN_ARROW("⬇️", "向下箭头"),
    DOWN_LEFT_ARROW("↙️", "左下箭头"),
    LEFT_ARROW("⬅️", "向左箭头"),
    UP_LEFT_ARROW("↖️", "左上箭头"),
    UP_DOWN_ARROW("↕️", "上下箭头"),
    LEFT_RIGHT_ARROW("↔️", "左右箭头"),
    RIGHT_ARROW_CURVING_LEFT("↩️", "右转弯箭头"),
    LEFT_ARROW_CURVING_RIGHT("↪️", "左转弯箭头"),
    RIGHT_ARROW_CURVING_UP("⤴️", "右上弯箭头"),
    RIGHT_ARROW_CURVING_DOWN("⤵️", "右下弯箭头"),
    CLOCKWISE_VERTICAL_ARROWS("🔃", "顺时针垂直箭头"),
    COUNTERCLOCKWISE_ARROWS_BUTTON("🔄", "逆时针箭头按钮"),
    BACK_ARROW("🔙", "返回箭头"),
    END_ARROW("🔚", "结束箭头"),
    ON_ARROW("🔛", "ON! 箭头"),
    SOON_ARROW("🔜", "SOON 箭头"),
    TOP_ARROW("🔝", "置顶"),
    PLACE_OF_WORSHIP("🛐", "宗教场所"),
    ATOM_SYMBOL("⚛️", "原子符号"),
    OM("🕉️", "奥姆"),
    STAR_OF_DAVID("✡️", "六芒星"),
    WHEEL_OF_DHARMA("☸️", "法轮"),
    YIN_YANG("☯️", "阴阳"),
    LATIN_CROSS("✝️", "十字架"),
    ORTHODOX_CROSS("☦️", "东正教十字架"),
    STAR_AND_CRESCENT("☪️", "星月"),
    PEACE_SYMBOL("☮️", "和平符号"),
    MENORAH("🕎", "烛台"),
    DOTTED_SIX_POINTED_STAR("🔯", "带中间点的六芒星"),
    ARIES("♈", "白羊座"),
    TAURUS("♉", "金牛座"),
    GEMINI("♊", "双子座"),
    CANCER("♋", "巨蟹座"),
    LEO("♌", "狮子座"),
    VIRGO("♍", "处女座"),
    LIBRA("♎", "天秤座"),
    SCORPIO("♏", "天蝎座"),
    SAGITTARIUS("♐", "射手座"),
    CAPRICORN("♑", "摩羯座"),
    AQUARIUS("♒", "水瓶座"),
    PISCES("♓", "双鱼座"),
    OPHIUCHUS("⛎", "蛇夫座"),
    SHUFFLE_TRACKS_BUTTON("🔀", "随机播放音轨按钮"),
    REPEAT_BUTTON("🔁", "重复按钮"),
    REPEAT_SINGLE_BUTTON("🔂", "重复一次按钮"),
    PLAY_BUTTON("▶️", "播放按钮"),
    FAST_FORWARD_BUTTON("⏩", "快进按钮"),
    NEXT_TRACK_BUTTON("⏭️", "下一个音轨按钮"),
    PLAY_OR_PAUSE_BUTTON("⏯️", "播放或暂停按钮"),
    REVERSE_BUTTON("◀️", "倒退按钮"),
    FAST_REVERSE_BUTTON("⏪", "快退按钮"),
    LAST_TRACK_BUTTON("⏮️", "上一个音轨按钮"),
    UPWARDS_BUTTON("🔼", "向上三角形按钮"),
    FAST_UP_BUTTON("⏫", "快速上升按钮"),
    DOWNWARDS_BUTTON("🔽", "向下三角形按钮"),
    FAST_DOWN_BUTTON("⏬", "快速下降按钮"),
    PAUSE_BUTTON("⏸️", "暂停按钮"),
    STOP_BUTTON("⏹️", "停止按钮"),
    RECORD_BUTTON("⏺️", "录制按钮"),
    EJECT_BUTTON("⏏️", "推出按钮"),
    CINEMA("🎦", "电影院"),
    DIM_BUTTON("🔅", "低亮度按钮"),
    BRIGHT_BUTTON("🔆", "高亮度按钮"),
    ANTENNA_BARS("📶", "信号强度条"),
    VIBRATION_MODE("📳", "振动模式"),
    MOBILE_PHONE_OFF("📴", "手机关机"),
    FEMALE_SIGN("♀️", "女性符号"),
    MALE_SIGN("♂️", "男性符号"),
    TRANSGENDER_SYMBOL("⚧️", "跨性别符号"),
    KEYCAP_SHELL("#️⃣", "按键: #"),
    KEYCAP_STAR("*️⃣", "按键: *"),
    KEYCAP_0("0️⃣", "按键: 0"),
    KEYCAP_1("1️⃣", "按键: 1"),
    KEYCAP_2("2️⃣", "按键: 2"),
    KEYCAP_3("3️⃣", "按键: 3"),
    KEYCAP_4("4️⃣", "按键: 4"),
    KEYCAP_5("5️⃣", "按键: 5"),
    KEYCAP_6("6️⃣", "按键: 6"),
    KEYCAP_7("7️⃣", "按键: 7"),
    KEYCAP_8("8️⃣", "按键: 8"),
    KEYCAP_9("9️⃣", "按键: 9"),
    KEYCAP_10("🔟", "按键: 10"),
    INPUT_LATIN_UPPERCASE("🔠", "输入大写拉丁字母"),
    INPUT_LATIN_LOWERCASE("🔡", "输入小写拉丁字母"),
    INPUT_NUMBERS("🔢", "输入数字"),
    INPUT_SYMBOLS("🔣", "输入符号"),
    INPUT_LATIN_LETTERS("🔤", "输入拉丁字母"),
    A_BUTTON_BLOOD_TYPE("🅰️", "A型血"),
    AB_BUTTON_BLOOD_TYPE("🆎", "AB型血"),
    B_BUTTON_BLOOD_TYPE("🅱️", "B型血"),
    CL_BUTTON("🆑", "CL按钮"),
    COOL_BUTTON("🆒", "cool按钮"),
    FREE_BUTTON("🆓", "免费按钮"),
    INFORMATION("ℹ️", "信息"),
    ID_BUTTON("🆔", "ID按钮"),
    CIRCLED_M("Ⓜ️", "圆圈包围的M"),
    NEW_BUTTON("🆕", "new按钮"),
    NG_BUTTON("🆖", "NG按钮"),
    O_BUTTON_BLOOD_TYPE("🅾️", "O 型血"),
    OK_BUTTON("🆗", "OK按钮"),
    P_BUTTON("🅿️", "停车按钮"),
    SOS_BUTTON("🆘", "SOS按钮"),
    UP_BUTTON("🆙", "up按钮"),
    VS_BUTTON("🆚", "VS按钮"),
    JAPANESE_HERE_BUTTON("🈁", "日文的“这里”按钮"),
    JAPANESE_SERVICE_CHARGE_BUTTON("🈂️", "日文的“服务费”按钮"),
    JAPANESE_MONTHLY_AMOUNT_BUTTON("🈷️", "日文的“月总量”按钮"),
    JAPANESE_NOT_FREE_OF_CHARGE_BUTTON("🈶", "日文的“收费”按钮"),
    JAPANESE_RESERVED_BUTTON("🈯", "日文的“预留”按钮"),
    JAPANESE_BARGAIN_BUTTON("🉐", "日文的“议价”按钮"),
    JAPANESE_DISCOUNT_BUTTON("🈹", "日文的“打折”按钮"),
    JAPANESE_FREE_OF_CHARGE_BUTTON("🈚", "日文的“免费”按钮"),
    JAPANESE_PROHIBITED_BUTTON("🈲", "日文的“禁止”按钮"),
    JAPANESE_ACCEPTABLE_BUTTON("🉑", "日文的“可接受”按钮"),
    JAPANESE_APPLICATION_BUTTON("🈸", "日文的“申请”按钮"),
    JAPANESE_PASSING_GRADE_BUTTON("🈴", "日文的“合格”按钮"),
    JAPANESE_VACANCY_BUTTON("🈳", "日文的“有空位”按钮"),
    JAPANESE_CONGRATULATIONS_BUTTON("㊗️", "日文的“祝贺”按钮"),
    JAPANESE_SECRET_BUTTON("㊙️", "日文的“秘密”按钮"),
    JAPANESE_OPEN_FOR_BUSINESS_BUTTON("🈺", "日文的“开始营业”按钮"),
    JAPANESE_NO_VACANCY_BUTTON("🈵", "日文的“没有空位”按钮"),
    RED_CIRCLE("🔴", "红色圆"),
    ORANGE_CIRCLE("🟠", "橙色圆"),
    YELLOW_CIRCLE("🟡", "黄色圆"),
    GREEN_CIRCLE("🟢", "绿色圆"),
    BLUE_CIRCLE("🔵", "蓝色圆"),
    PURPLE_CIRCLE("🟣", "紫色圆"),
    BROWN_CIRCLE("🟤", "棕色圆"),
    BLACK_CIRCLE("⚫", "黑色圆"),
    WHITE_CIRCLE("⚪", "白色圆"),
    RED_SQUARE("🟥", "红色方块"),
    ORANGE_SQUARE("🟧", "橙色方块"),
    YELLOW_SQUARE("🟨", "黄色方块"),
    GREEN_SQUARE("🟩", "绿色方块"),
    BLUE_SQUARE("🟦", "蓝色方块"),
    PURPLE_SQUARE("🟪", "紫色方块"),
    BROWN_SQUARE("🟫", "棕色方块"),
    BLACK_LARGE_SQUARE("⬛", "黑线大方框"),
    WHITE_LARGE_SQUARE("⬜", "白线大方框"),
    BLACK_MEDIUM_SQUARE("◼️", "黑色中方块"),
    WHITE_MEDIUM_SQUARE("◻️", "白色中方块"),
    BLACK_MEDIUM_SMALL_SQUARE("◾", "黑色中小方块"),
    WHITE_MEDIUM_SMALL_SQUARE("◽", "白色中小方块"),
    BLACK_SMALL_SQUARE("▪️", "黑色小方块"),
    WHITE_SMALL_SQUARE("▫️", "白色小方块"),
    LARGE_ORANGE_DIAMOND("🔶", "橙色大菱形"),
    LARGE_BLUE_DIAMOND("🔷", "蓝色大菱形"),
    SMALL_ORANGE_DIAMOND("🔸", "橙色小菱形"),
    SMALL_BLUE_DIAMOND("🔹", "蓝色小菱形"),
    RED_TRIANGLE_POINTED_UP("🔺", "红色正三角"),
    RED_TRIANGLE_POINTED_DOWN("🔻", "红色倒三角"),
    DIAMOND_WITH_A_DOT("💠", "带圆点的菱形"),
    RADIO_BUTTON("🔘", "单选按钮"),
    WHITE_SQUARE_BUTTON("🔳", "白色方形按钮"),
    BLACK_SQUARE_BUTTON("🔲", "黑色方形按钮"),
    INFINITY("♾️", "无穷大"),
    MULTIPLY("✖️", "乘"),
    PLUS("➕", "加"),
    MINUS("➖", "减"),
    DIVIDE("➗", "除"),
    CURRENCY_EXCHANGE("💱", "货币兑换"),
    HEAVY_DOLLAR_SIGN("💲", "粗美元符号"),
    DOUBLE_EXCLAMATION_MARK("‼️", "双感叹号"),
    EXCLAMATION_QUESTION_MARK("⁉️", "感叹疑问号"),
    RED_QUESTION_MARK("❓", "红色问号"),
    WHITE_QUESTION_MARK("❔", "白色问号"),
    WHITE_EXCLAMATION_MARK("❕", "白色感叹号"),
    RED_EXCLAMATION_MARK("❗", "红色感叹号"),
    WAVY_DASH("〰️", "波浪型破折号"),
    MEDICAL_SYMBOL("⚕️", "医疗标志"),
    RECYCLING_SYMBOL("♻️", "回收标志"),
    FLEUR_DE_LIS("⚜️", "百合花饰"),
    TRIDENT_EMBLEM("🔱", "三叉戟徽章"),
    NAME_BADGE("📛", "姓名牌"),
    JAPANESE_SYMBOL_FOR_BEGINNER("🔰", "日本新手驾驶标志"),
    HOLLOW_RED_CIRCLE("⭕", "红色空心圆圈"),
    CHECK_MARK_BUTTON("✅", "勾号按钮"),
    CHECK_BOX_WITH_CHECK("☑️", "勾选框"),
    CHECK_MARK("✔️", "勾号"),
    CROSS_MARK("❌", "叉号"),
    CROSS_MARK_BUTTON("❎", "叉号按钮"),
    CURLY_LOOP("➰", "卷曲环"),
    DOUBLE_CURLY_LOOP("➿", "双卷曲环"),
    PART_ALTERNATION_MARK("〽️", "庵点"),
    EIGHT_SPOKED_ASTERISK("✳️", "八轮辐星号"),
    EIGHT_POINTED_STAR("✴️", "八角星"),
    SPARKLE("❇️", "火花"),
    COPYRIGHT("©️", "版权"),
    REGISTERED("®️", "注册"),
    TRADE_MARK("™️", "商标"),
}

/* 旗帜 */
enum class FlagsEmoji(
    val emojiContext: String,
    val emojiDescription: String
) : MyEmoji {
    CHEQUERED_FLAG("🏁", "终点旗"),
    TRIANGULAR_FLAG("🚩", "三角旗"),
    CROSSED_FLAGS("🎌", "交叉旗"),
    BLACK_FLAG("🏴", "举黑旗"),
    WHITE_FLAG("🏳️", "举白旗"),
    RAINBOW_FLAG("🏳️‍🌈", "彩虹旗"),
    PIRATE_FLAG("🏴‍☠️", "海盗旗"),
    TRANSGENDER_FLAG("🏳️‍⚧️", "跨性别旗"),
    FLAG_ASCENSION_ISLAND("🇦🇨", "旗: 阿森松岛"),
    FLAG_ANDORRA("🇦🇩", "旗: 安道尔"),
    FLAG_UNITED_ARAB_EMIRATES("🇦🇪", "旗: 阿拉伯联合酋长国"),
    FLAG_AFGHANISTAN("🇦🇫", "旗: 阿富汗"),
    FLAG_ANTIGUA_BARBUDA("🇦🇬", "旗: 安提瓜和巴布达"),
    FLAG_ANGUILLA("🇦🇮", "旗: 安圭拉"),
    FLAG_ALBANIA("🇦🇱", "旗: 阿尔巴尼亚"),
    FLAG_ARMENIA("🇦🇲", "旗: 亚美尼亚"),
    FLAG_ANGOLA("🇦🇴", "旗: 安哥拉"),
    FLAG_ANTARCTICA("🇦🇶", "旗: 南极洲"),
    FLAG_ARGENTINA("🇦🇷", "旗: 阿根廷"),
    FLAG_AMERICAN_SAMOA("🇦🇸", "旗: 美属萨摩亚"),
    FLAG_AUSTRIA("🇦🇹", "旗: 奥地利"),
    FLAG_AUSTRALIA("🇦🇺", "旗: 澳大利亚"),
    FLAG_ARUBA("🇦🇼", "旗: 阿鲁巴"),
    FLAG_ÅLAND_ISLANDS("🇦🇽", "旗: 奥兰群岛"),
    FLAG_AZERBAIJAN("🇦🇿", "旗: 阿塞拜疆"),
    FLAG_BOSNIA_HERZEGOVINA("🇧🇦", "旗: 波斯尼亚和黑塞哥维那"),
    FLAG_BARBADOS("🇧🇧", "旗: 巴巴多斯"),
    FLAG_BANGLADESH("🇧🇩", "旗: 孟加拉国"),
    FLAG_BELGIUM("🇧🇪", "旗: 比利时"),
    FLAG_BURKINA_FASO("🇧🇫", "旗: 布基纳法索"),
    FLAG_BULGARIA("🇧🇬", "旗: 保加利亚"),
    FLAG_BAHRAIN("🇧🇭", "旗: 巴林"),
    FLAG_BURUNDI("🇧🇮", "旗: 布隆迪"),
    FLAG_BENIN("🇧🇯", "旗: 贝宁"),
    FLAG_ST_BARTHÉLEMY("🇧🇱", "旗: 圣巴泰勒米"),
    FLAG_BERMUDA("🇧🇲", "旗: 百慕大"),
    FLAG_BRUNEI("🇧🇳", "旗: 文莱"),
    FLAG_BOLIVIA("🇧🇴", "旗: 玻利维亚"),
    FLAG_CARIBBEAN_NETHERLANDS("🇧🇶", "旗: 荷属加勒比区"),
    FLAG_BRAZIL("🇧🇷", "旗: 巴西"),
    FLAG_BAHAMAS("🇧🇸", "旗: 巴哈马"),
    FLAG_BHUTAN("🇧🇹", "旗: 不丹"),
    FLAG_BOUVET_ISLAND("🇧🇻", "旗: 布韦岛"),
    FLAG_BOTSWANA("🇧🇼", "旗: 博茨瓦纳"),
    FLAG_BELARUS("🇧🇾", "旗: 白俄罗斯"),
    FLAG_BELIZE("🇧🇿", "旗: 伯利兹"),
    FLAG_CANADA("🇨🇦", "旗: 加拿大"),
    FLAG_COCOS_KEELING_ISLANDS("🇨🇨", "旗: 科科斯（基林）群岛"),
    FLAG_CONGO_KINSHASA("🇨🇩", "旗: 刚果（金）"),
    FLAG_CENTRAL_AFRICAN_REPUBLIC("🇨🇫", "旗: 中非共和国"),
    FLAG_CONGO___BRAZZAVILLE("🇨🇬", "旗: 刚果（布）"),
    FLAG_SWITZERLAND("🇨🇭", "旗: 瑞士"),
    FLAG_CÔTE_D_IVOIRE("🇨🇮", "旗: 科特迪瓦"),
    FLAG_COOK_ISLANDS("🇨🇰", "旗: 库克群岛"),
    FLAG_CHILE("🇨🇱", "旗: 智利"),
    FLAG_CAMEROON("🇨🇲", "旗: 喀麦隆"),
    FLAG_CHINA("🇨🇳", "旗: 中国"),
    FLAG_COLOMBIA("🇨🇴", "旗: 哥伦比亚"),
    FLAG_CLIPPERTON_ISLAND("🇨🇵", "旗: 克利珀顿岛"),
    FLAG_COSTA_RICA("🇨🇷", "旗: 哥斯达黎加"),
    FLAG_CUBA("🇨🇺", "旗: 古巴"),
    FLAG_CAPE_VERDE("🇨🇻", "旗: 佛得角"),
    FLAG_CURAÇAO("🇨🇼", "旗: 库拉索"),
    FLAG_CHRISTMAS_ISLAND("🇨🇽", "旗: 圣诞岛"),
    FLAG_CYPRUS("🇨🇾", "旗: 塞浦路斯"),
    FLAG_CZECHIA("🇨🇿", "旗: 捷克"),
    FLAG_GERMANY("🇩🇪", "旗: 德国"),
    FLAG_DIEGO_GARCIA("🇩🇬", "旗: 迪戈加西亚岛"),
    FLAG_DJIBOUTI("🇩🇯", "旗: 吉布提"),
    FLAG_DENMARK("🇩🇰", "旗: 丹麦"),
    FLAG_DOMINICA("🇩🇲", "旗: 多米尼克"),
    FLAG_DOMINICAN_REPUBLIC("🇩🇴", "旗: 多米尼加共和国"),
    FLAG_ALGERIA("🇩🇿", "旗: 阿尔及利亚"),
    FLAG_CEUTA_MELILLA("🇪🇦", "旗: 休达及梅利利亚"),
    FLAG_ECUADOR("🇪🇨", "旗: 厄瓜多尔"),
    FLAG_ESTONIA("🇪🇪", "旗: 爱沙尼亚"),
    FLAG_EGYPT("🇪🇬", "旗: 埃及"),
    FLAG_WESTERN_SAHARA("🇪🇭", "旗: 西撒哈拉"),
    FLAG_ERITREA("🇪🇷", "旗: 厄立特里亚"),
    FLAG_SPAIN("🇪🇸", "旗: 西班牙"),
    FLAG_ETHIOPIA("🇪🇹", "旗: 埃塞俄比亚"),
    FLAG_EUROPEAN_UNION("🇪🇺", "旗: 欧盟"),
    FLAG_FINLAND("🇫🇮", "旗: 芬兰"),
    FLAG_FIJI("🇫🇯", "旗: 斐济"),
    FLAG_FALKLAND_ISLANDS("🇫🇰", "旗: 福克兰群岛"),
    FLAG_MICRONESIA("🇫🇲", "旗: 密克罗尼西亚"),
    FLAG_FAROE_ISLANDS("🇫🇴", "旗: 法罗群岛"),
    FLAG_FRANCE("🇫🇷", "旗: 法国"),
    FLAG_GABON("🇬🇦", "旗: 加蓬"),
    FLAG_UNITED_KINGDOM("🇬🇧", "旗: 英国"),
    FLAG_GRENADA("🇬🇩", "旗: 格林纳达"),
    FLAG_GEORGIA("🇬🇪", "旗: 格鲁吉亚"),
    FLAG_FRENCH_GUIANA("🇬🇫", "旗: 法属圭亚那"),
    FLAG_GUERNSEY("🇬🇬", "旗: 根西岛"),
    FLAG_GHANA("🇬🇭", "旗: 加纳"),
    FLAG_GIBRALTAR("🇬🇮", "旗: 直布罗陀"),
    FLAG_GREENLAND("🇬🇱", "旗: 格陵兰"),
    FLAG_GAMBIA("🇬🇲", "旗: 冈比亚"),
    FLAG_GUINEA("🇬🇳", "旗: 几内亚"),
    FLAG_GUADELOUPE("🇬🇵", "旗: 瓜德罗普"),
    FLAG_EQUATORIAL_GUINEA("🇬🇶", "旗: 赤道几内亚"),
    FLAG_GREECE("🇬🇷", "旗: 希腊"),
    FLAG_SOUTH_GEORGIA_SOUTH_SANDWICH_ISLANDS("🇬🇸", "旗: 南乔治亚和南桑威奇群岛"),
    FLAG_GUATEMALA("🇬🇹", "旗: 危地马拉"),
    FLAG_GUAM("🇬🇺", "旗: 关岛"),
    FLAG_GUINEA_BISSAU("🇬🇼", "旗: 几内亚比绍"),
    FLAG_GUYANA("🇬🇾", "旗: 圭亚那"),
    FLAG_HONG_KONG_SAR_CHINA("🇭🇰", "旗: 中国香港特别行政区"),
    FLAG_HEARD_MCDONALD_ISLANDS("🇭🇲", "旗: 赫德岛和麦克唐纳群岛"),
    FLAG_HONDURAS("🇭🇳", "旗: 洪都拉斯"),
    FLAG_CROATIA("🇭🇷", "旗: 克罗地亚"),
    FLAG_HAITI("🇭🇹", "旗: 海地"),
    FLAG_HUNGARY("🇭🇺", "旗: 匈牙利"),
    FLAG_CANARY_ISLANDS("🇮🇨", "旗: 加纳利群岛"),
    FLAG_INDONESIA("🇮🇩", "旗: 印度尼西亚"),
    FLAG_IRELAND("🇮🇪", "旗: 爱尔兰"),
    FLAG_ISRAEL("🇮🇱", "旗: 以色列"),
    FLAG_ISLE_OF_MAN("🇮🇲", "旗: 马恩岛"),
    FLAG_INDIA("🇮🇳", "旗: 印度"),
    FLAG_BRITISH_INDIAN_OCEAN_TERRITORY("🇮🇴", "旗: 英属印度洋领地"),
    FLAG_IRAQ("🇮🇶", "旗: 伊拉克"),
    FLAG_IRAN("🇮🇷", "旗: 伊朗"),
    FLAG_ICELAND("🇮🇸", "旗: 冰岛"),
    FLAG_ITALY("🇮🇹", "旗: 意大利"),
    FLAG_JERSEY("🇯🇪", "旗: 泽西岛"),
    FLAG_JAMAICA("🇯🇲", "旗: 牙买加"),
    FLAG_JORDAN("🇯🇴", "旗: 约旦"),
    FLAG_JAPAN("🇯🇵", "旗: 日本"),
    FLAG_KENYA("🇰🇪", "旗: 肯尼亚"),
    FLAG_KYRGYZSTAN("🇰🇬", "旗: 吉尔吉斯斯坦"),
    FLAG_CAMBODIA("🇰🇭", "旗: 柬埔寨"),
    FLAG_KIRIBATI("🇰🇮", "旗: 基里巴斯"),
    FLAG_COMOROS("🇰🇲", "旗: 科摩罗"),
    FLAG_ST_KITTS_NEVIS("🇰🇳", "旗: 圣基茨和尼维斯"),
    FLAG_NORTH_KOREA("🇰🇵", "旗: 朝鲜"),
    FLAG_SOUTH_KOREA("🇰🇷", "旗: 韩国"),
    FLAG_KUWAIT("🇰🇼", "旗: 科威特"),
    FLAG_CAYMAN_ISLANDS("🇰🇾", "旗: 开曼群岛"),
    FLAG_KAZAKHSTAN("🇰🇿", "旗: 哈萨克斯坦"),
    FLAG_LAOS("🇱🇦", "旗: 老挝"),
    FLAG_LEBANON("🇱🇧", "旗: 黎巴嫩"),
    FLAG_ST_LUCIA("🇱🇨", "旗: 圣卢西亚"),
    FLAG_LIECHTENSTEIN("🇱🇮", "旗: 列支敦士登"),
    FLAG_SRI_LANKA("🇱🇰", "旗: 斯里兰卡"),
    FLAG_LIBERIA("🇱🇷", "旗: 利比里亚"),
    FLAG_LESOTHO("🇱🇸", "旗: 莱索托"),
    FLAG_LITHUANIA("🇱🇹", "旗: 立陶宛"),
    FLAG_LUXEMBOURG("🇱🇺", "旗: 卢森堡"),
    FLAG_LATVIA("🇱🇻", "旗: 拉脱维亚"),
    FLAG_LIBYA("🇱🇾", "旗: 利比亚"),
    FLAG_MOROCCO("🇲🇦", "旗: 摩洛哥"),
    FLAG_MONACO("🇲🇨", "旗: 摩纳哥"),
    FLAG_MOLDOVA("🇲🇩", "旗: 摩尔多瓦"),
    FLAG_MONTENEGRO("🇲🇪", "旗: 黑山"),
    FLAG_ST_MARTIN("🇲🇫", "旗: 法属圣马丁"),
    FLAG_MADAGASCAR("🇲🇬", "旗: 马达加斯加"),
    FLAG_MARSHALL_ISLANDS("🇲🇭", "旗: 马绍尔群岛"),
    FLAG_NORTH_MACEDONIA("🇲🇰", "旗: 北马其顿"),
    FLAG_MALI("🇲🇱", "旗: 马里"),
    FLAG_MYANMAR_BURMA("🇲🇲", "旗: 缅甸"),
    FLAG_MONGOLIA("🇲🇳", "旗: 蒙古"),
    FLAG_MACAO_SAR_CHINA("🇲🇴", "旗: 中国澳门特别行政区"),
    FLAG_NORTHERN_MARIANA_ISLANDS("🇲🇵", "旗: 北马里亚纳群岛"),
    FLAG_MARTINIQUE("🇲🇶", "旗: 马提尼克"),
    FLAG_MAURITANIA("🇲🇷", "旗: 毛里塔尼亚"),
    FLAG_MONTSERRAT("🇲🇸", "旗: 蒙特塞拉特"),
    FLAG_MALTA("🇲🇹", "旗: 马耳他"),
    FLAG_MAURITIUS("🇲🇺", "旗: 毛里求斯"),
    FLAG_MALDIVES("🇲🇻", "旗: 马尔代夫"),
    FLAG_MALAWI("🇲🇼", "旗: 马拉维"),
    FLAG_MEXICO("🇲🇽", "旗: 墨西哥"),
    FLAG_MALAYSIA("🇲🇾", "旗: 马来西亚"),
    FLAG_MOZAMBIQUE("🇲🇿", "旗: 莫桑比克"),
    FLAG_NAMIBIA("🇳🇦", "旗: 纳米比亚"),
    FLAG_NEW_CALEDONIA("🇳🇨", "旗: 新喀里多尼亚"),
    FLAG_NIGER("🇳🇪", "旗: 尼日尔"),
    FLAG_NORFOLK_ISLAND("🇳🇫", "旗: 诺福克岛"),
    FLAG_NIGERIA("🇳🇬", "旗: 尼日利亚"),
    FLAG_NICARAGUA("🇳🇮", "旗: 尼加拉瓜"),
    FLAG_NETHERLANDS("🇳🇱", "旗: 荷兰"),
    FLAG_NORWAY("🇳🇴", "旗: 挪威"),
    FLAG_NEPAL("🇳🇵", "旗: 尼泊尔"),
    FLAG_NAURU("🇳🇷", "旗: 瑙鲁"),
    FLAG_NIUE("🇳🇺", "旗: 纽埃"),
    FLAG_NEW_ZEALAND("🇳🇿", "旗: 新西兰"),
    FLAG_OMAN("🇴🇲", "旗: 阿曼"),
    FLAG_PANAMA("🇵🇦", "旗: 巴拿马"),
    FLAG_PERU("🇵🇪", "旗: 秘鲁"),
    FLAG_FRENCH_POLYNESIA("🇵🇫", "旗: 法属波利尼西亚"),
    FLAG_PAPUA_NEW_GUINEA("🇵🇬", "旗: 巴布亚新几内亚"),
    FLAG_PHILIPPINES("🇵🇭", "旗: 菲律宾"),
    FLAG_PAKISTAN("🇵🇰", "旗: 巴基斯坦"),
    FLAG_POLAND("🇵🇱", "旗: 波兰"),
    FLAG_ST_PIERRE_MIQUELON("🇵🇲", "旗: 圣皮埃尔和密克隆群岛"),
    FLAG_PITCAIRN_ISLANDS("🇵🇳", "旗: 皮特凯恩群岛"),
    FLAG_PUERTO_RICO("🇵🇷", "旗: 波多黎各"),
    FLAG_PALESTINIAN_TERRITORIES("🇵🇸", "旗: 巴勒斯坦领土"),
    FLAG_PORTUGAL("🇵🇹", "旗: 葡萄牙"),
    FLAG_PALAU("🇵🇼", "旗: 帕劳"),
    FLAG_PARAGUAY("🇵🇾", "旗: 巴拉圭"),
    FLAG_QATAR("🇶🇦", "旗: 卡塔尔"),
    FLAG_RÉUNION("🇷🇪", "旗: 留尼汪"),
    FLAG_ROMANIA("🇷🇴", "旗: 罗马尼亚"),
    FLAG_SERBIA("🇷🇸", "旗: 塞尔维亚"),
    FLAG_RUSSIA("🇷🇺", "旗: 俄罗斯"),
    FLAG_RWANDA("🇷🇼", "旗: 卢旺达"),
    FLAG_SAUDI_ARABIA("🇸🇦", "旗: 沙特阿拉伯"),
    FLAG_SOLOMON_ISLANDS("🇸🇧", "旗: 所罗门群岛"),
    FLAG_SEYCHELLES("🇸🇨", "旗: 塞舌尔"),
    FLAG_SUDAN("🇸🇩", "旗: 苏丹"),
    FLAG_SWEDEN("🇸🇪", "旗: 瑞典"),
    FLAG_SINGAPORE("🇸🇬", "旗: 新加坡"),
    FLAG_ST_HELENA("🇸🇭", "旗: 圣赫勒拿"),
    FLAG_SLOVENIA("🇸🇮", "旗: 斯洛文尼亚"),
    FLAG_SVALBARD_JAN_MAYEN("🇸🇯", "旗: 斯瓦尔巴和扬马延"),
    FLAG_SLOVAKIA("🇸🇰", "旗: 斯洛伐克"),
    FLAG_SIERRA_LEONE("🇸🇱", "旗: 塞拉利昂"),
    FLAG_SAN_MARINO("🇸🇲", "旗: 圣马力诺"),
    FLAG_SENEGAL("🇸🇳", "旗: 塞内加尔"),
    FLAG_SOMALIA("🇸🇴", "旗: 索马里"),
    FLAG_SURINAME("🇸🇷", "旗: 苏里南"),
    FLAG_SOUTH_SUDAN("🇸🇸", "旗: 南苏丹"),
    FLAG_SÃO_TOMÉ_PRÍNCIPE("🇸🇹", "旗: 圣多美和普林西比"),
    FLAG_EL_SALVADOR("🇸🇻", "旗: 萨尔瓦多"),
    FLAG_SINT_MAARTEN("🇸🇽", "旗: 荷属圣马丁"),
    FLAG_SYRIA("🇸🇾", "旗: 叙利亚"),
    FLAG_ESWATINI("🇸🇿", "旗: 斯威士兰"),
    FLAG_TRISTAN_DA_CUNHA("🇹🇦", "旗: 特里斯坦-达库尼亚群岛"),
    FLAG_TURKS_CAICOS_ISLANDS("🇹🇨", "旗: 特克斯和凯科斯群岛"),
    FLAG_CHAD("🇹🇩", "旗: 乍得"),
    FLAG_FRENCH_SOUTHERN_TERRITORIES("🇹🇫", "旗: 法属南部领地"),
    FLAG_TOGO("🇹🇬", "旗: 多哥"),
    FLAG_THAILAND("🇹🇭", "旗: 泰国"),
    FLAG_TAJIKISTAN("🇹🇯", "旗: 塔吉克斯坦"),
    FLAG_TOKELAU("🇹🇰", "旗: 托克劳"),
    FLAG_TIMOR_LESTE("🇹🇱", "旗: 东帝汶"),
    FLAG_TURKMENISTAN("🇹🇲", "旗: 土库曼斯坦"),
    FLAG_TUNISIA("🇹🇳", "旗: 突尼斯"),
    FLAG_TONGA("🇹🇴", "旗: 汤加"),
    FLAG_TURKEY("🇹🇷", "旗: 土耳其"),
    FLAG_TRINIDAD_TOBAGO("🇹🇹", "旗: 特立尼达和多巴哥"),
    FLAG_TUVALU("🇹🇻", "旗: 图瓦卢"),
    FLAG_TAIWAN("🇹🇼", "旗: 台湾"),
    FLAG_TANZANIA("🇹🇿", "旗: 坦桑尼亚"),
    FLAG_UKRAINE("🇺🇦", "旗: 乌克兰"),
    FLAG_UGANDA("🇺🇬", "旗: 乌干达"),
    FLAG_US_OUTLYING_ISLANDS("🇺🇲", "旗: 美国本土外小岛屿"),
    FLAG_UNITED_NATIONS("🇺🇳", "旗: 联合国"),
    FLAG_UNITED_STATES("🇺🇸", "旗: 美国"),
    FLAG_URUGUAY("🇺🇾", "旗: 乌拉圭"),
    FLAG_UZBEKISTAN("🇺🇿", "旗: 乌兹别克斯坦"),
    FLAG_VATICAN_CITY("🇻🇦", "旗: 梵蒂冈"),
    FLAG_ST_VINCENT_GRENADINES("🇻🇨", "旗: 圣文森特和格林纳丁斯"),
    FLAG_VENEZUELA("🇻🇪", "旗: 委内瑞拉"),
    FLAG_BRITISH_VIRGIN_ISLANDS("🇻🇬", "旗: 英属维尔京群岛"),
    FLAG_US_VIRGIN_ISLANDS("🇻🇮", "旗: 美属维尔京群岛"),
    FLAG_VIETNAM("🇻🇳", "旗: 越南"),
    FLAG_VANUATU("🇻🇺", "旗: 瓦努阿图"),
    FLAG_WALLIS_FUTUNA("🇼🇫", "旗: 瓦利斯和富图纳"),
    FLAG_SAMOA("🇼🇸", "旗: 萨摩亚"),
    FLAG_KOSOVO("🇽🇰", "旗: 科索沃"),
    FLAG_YEMEN("🇾🇪", "旗: 也门"),
    FLAG_MAYOTTE("🇾🇹", "旗: 马约特"),
    FLAG_SOUTH_AFRICA("🇿🇦", "旗: 南非"),
    FLAG_ZAMBIA("🇿🇲", "旗: 赞比亚"),
    FLAG_ZIMBABWE("🇿🇼", "旗: 津巴布韦"),
    FLAG_ENGLAND("🏴󠁧󠁢󠁥󠁮󠁧󠁿", "旗: 英格兰"),
    FLAG_SCOTLAND("🏴󠁧󠁢󠁳󠁣󠁴󠁿", "旗: 苏格兰"),
    FLAG_WALES("🏴󠁧󠁢󠁷󠁬󠁳󠁿", "旗: 威尔士"),
}